### ISSUE TITLE
Importing XML through the MGCB processor - errors

### ISSUE THREAD

**Issue by DDReaper** [mono/MonoGame#3404]
From one fire to the next.  I'm converting an old XNA 4 project to MonoGame and running in to issues with the XML importer.  

SO far I have two issues (which were not an issue in the original XNA XML content importer.

1: "Not have enough entries in space-separated list!"
this seems related to how certain data types are imported, e.g. A vector 2 is expected to be 2 integers space separated.
The source XML hasn't changed but with the MGCB processor it is  falling over.

2: The Xml element `<item>` is required!
Although this imported fine in XNA, which ignored missing values.  With the MGCB importer, it seems to be forcing the XML de-serialisation to make all fields mandatory

Any ideas on these.  I would rather not have to go and edit the hundreds of XML configuration files used in this project, especially since they worked fine previously.

**Comment by DDReaper** [comment]
Hmm, on issue 2, the rabbit hole goes a bit further.  It seems the XML importer is not registering and using the following attribute:
[ContentSerializer(ElementName = "<name>")]

So this error is simply occurring because the data is using a different name to the actual data field.
For example:
        [ContentSerializer(ElementName = "Wapoints")]
        private Node[] _Waypoints;

(don't ask why they are different, that is a very long story)  but the short of it is that the data is set as per the ContentSerializer Element Name property whereas the class stores it as the property name.

Any ideas?

**Comment by tomspilman** [comment]
First are you using the latest development build?

> 1: "Not have enough entries in space-separated list!"

We have a pretty huge unit test for XML deserialization which covers Vector2...
 https://github.com/mono/MonoGame/blob/develop/Test/ContentPipeline/IntermediateDeserializerTest.cs#L255

So i'm surprised you're having trouble with it.

Can you post what your XML file looks like here?

> it seems to be forcing the XML de-serialisation to make all fields mandatory

There are some that are mandatory even in XNA.  I would have to see the specific case.

**Comment by tomspilman** [comment]
This all sounds to me like you are using a very old version of the content pipeline.

Everything you've mentioned are things covered in the unit tests.

**Comment by DDReaper** [comment]
Using the very latest dev build from the site @tomspilman 
Samples.
Right, the one currently failing for deserialising Vector2's is this file.

```xml
<?xml version="1.0" encoding="utf-8" ?>
<XnaContent>
  <Asset Type="ReturnToZero.Units.WaveDefinition">
    <WaveInfo>
      <!-- SET 0-->
      0 6
      0 8
      0 9
      0 10
      1 10
      1 10
      1 11
      1 12
      1 15
      1 15
    </WaveInfo>
  </Asset>
</XnaContent>
```

So although the XNA pipeline could read the space separated Vector 2's the MGCB processor can't?

**Comment by tomspilman** [comment]
Can you show me the type for `<WaveInfo>`?  I assume `List<Vector2>`?

**Comment by DDReaper** [comment]
Yup, pretty much

```csharp
    public class WaveDefinition
    {
        private List<Vector2> _WaveDefinition;

        public List<Vector2> WaveInfo
        {
            set { _WaveDefinition = value; }
            get { return _WaveDefinition; }
        }

        public WaveDefinition()
        {
            
        }
    }
```

**Comment by DDReaper** [comment]
Interesting note @tomspilman, the Vector2 type isn't tested in that UnitTest

```xml
            DeserializeCompileAndLoad<MathTypes>("12_MathTypes.xml", mathTypes =>
            {
                Assert.AreEqual(new Point(1, 2), mathTypes.Point);
                Assert.AreEqual(new Rectangle(1, 2, 3, 4), mathTypes.Rectangle);
                Assert.AreEqual(new Vector3(1, 2, 3.1f), mathTypes.Vector3);
                Assert.AreEqual(new Vector4(1, 2, 3, 4), mathTypes.Vector4);
                Assert.AreEqual(new Quaternion(1, 2, 3, 4), mathTypes.Quaternion);
                Assert.AreEqual(new Plane(1, 2, 3, 4), mathTypes.Plane);
                Assert.AreEqual(new Matrix(1, 2, 3, 4, 5 , 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16), mathTypes.Matrix);
                Assert.AreEqual(Color.CornflowerBlue, mathTypes.Color);
                Assert.NotNull(mathTypes.Vector2Array);
                Assert.AreEqual(2, mathTypes.Vector2Array.Length);
                Assert.AreEqual(Vector2.Zero, mathTypes.Vector2Array[0]);
                Assert.AreEqual(Vector2.One, mathTypes.Vector2Array[1]);
            });
```
But the other Vector types are (unless I'm reading that completely wrong)
There are some tests to test  Vector2array

Double checked the test XML file to be sire and it also doesn't have a Vector2 type

**Comment by theZMan** [comment]
XNAs intermediate serializer has some special optimisations to make the files smaller by allowing these space delimited things see http://blogs.msdn.com/b/shawnhar/archive/2008/07/28/intermediateserializer-vs-xmlserializer.aspx and http://blogs.msdn.com/b/shawnhar/archive/2008/08/12/everything-you-ever-wanted-to-know-about-intermediateserializer.aspx

Not sure if all these special cases are in the tests or if they just test 'normal' xml

**Comment by tomspilman** [comment]
So we have a test for Vector2 array...

https://github.com/mono/MonoGame/blob/develop/Test/ContentPipeline/AssetTestClasses.cs#L177

... but not really a test for `List<Vector2>`.  Seems like this could be specific to it.

However getting this fixed is easy.  We reproduce the failed case in the existing unit tests and then go about fixing the code.

I don't have time today, but I can get to it over the weekend.

**Comment by DDReaper** [comment]
Ok, thanks @tomspilman 
Now I know where to look, I'll see if I can get the test case to fail and see why it's happening.
Shouldn't make a difference if it's a Vector2 array or List really

**Comment by DDReaper** [comment]
Right (that was fun), so the error seems limited to when you use new lines for each Vector2 element
If you have a Vector2 List recorded as follows:
```xml
    <Vector2List>0 4 0 6 0 7 1 7 1 9 1 10 1 12 1 13 1 18 1 22</Vector2List>
```
It is able to read the list of Vector 2 values in to the List
However if the data is recorded like this:
```xml
    <Vector2ListSpaced>
      0 4
      0 6
      0 7
      1 7
      1 9
      1 10
      1 12
      1 13
      1 18
      1 22
      </Vector2ListSpaced>
```
It fails with the following error:
> Test Name:	MathTypes
> Test FullName:	MonoGame.Tests.ContentPipeline.IntermediateDeserializerTest.MathTypes
> Test Source:	c:\Development\GitHub\MonoGame\Test\ContentPipeline\IntermediateDeserializerTest.cs : line 250
> Test Outcome:	Failed
> Test Duration:	0:00:00.165

> Result Message:	System.FormatException : Input string was not in a correct format.
> Result StackTrace:	
> at System.Number.ParseSingle(String value, NumberStyles options, NumberFormatInfo numfmt)
> at System.Single.Parse(String s, NumberStyles style, IFormatProvider provider)
> at System.Xml.XmlConvert.ToSingle(String s)
> at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.Vector2Serializer.Deserialize(String[] inputs, Int32& index) in c:\Development\GitHub\MonoGame\MonoGame.Framework.Content.Pipeline\Serialization\Intermediate\Vector2Serializer.cs:line 20
at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.ElementSerializer`1.Deserialize(IntermediateReader input, List`1 results) in c:\Development\GitHub\MonoGame\MonoGame.Framework.Content.Pipeline\Serialization\Intermediate\ElementSerializerT.cs:line 54
at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.ListSerializer`1.Deserialize(IntermediateReader input, ContentSerializerAttribute format, List`1 existingInstance) in c:\Development\GitHub\MonoGame\MonoGame.Framework.Content.Pipeline\Serialization\Intermediate\ListSerializer.cs:line 36
at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.ContentTypeSerializer`1.Deserialize(IntermediateReader input, ContentSerializerAttribute format, Object existingInstance) in c:\Development\GitHub\MonoGame\MonoGame.Framework.Content.Pipeline\Serialization\Intermediate\ContentTypeSerializerT.cs:line 26
at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.IntermediateReader.ReadRawObject[T](ContentSerializerAttribute format, ContentTypeSerializer typeSerializer, T existingInstance) in c:\Development\GitHub\MonoGame\MonoGame.Framework.Content.Pipeline\Serialization\Intermediate\IntermediateReader.cs:line 115
at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.IntermediateReader.ReadObject[T](ContentSerializerAttribute format, ContentTypeSerializer typeSerializer, T existingInstance) in c:\Development\GitHub\MonoGame\MonoGame.Framework.Content.Pipeline\Serialization\Intermediate\IntermediateReader.cs:line 82
at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.IntermediateReader.ReadObject[T](ContentSerializerAttribute format, ContentTypeSerializer typeSerializer) in c:\Development\GitHub\MonoGame\MonoGame.Framework.Content.Pipeline\Serialization\Intermediate\IntermediateReader.cs:line 47
at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.ReflectiveSerializer.Deserialize(IntermediateReader input, ContentSerializerAttribute format, Object existingInstance) in c:\Development\GitHub\MonoGame\MonoGame.Framework.Content.Pipeline\Serialization\Intermediate\ReflectiveSerializer.cs:line 172
at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.IntermediateReader.ReadRawObject[T](ContentSerializerAttribute format, ContentTypeSerializer typeSerializer, T existingInstance) in c:\Development\GitHub\MonoGame\MonoGame.Framework.Content.Pipeline\Serialization\Intermediate\IntermediateReader.cs:line 115
at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.IntermediateReader.ReadObject[T](ContentSerializerAttribute format, ContentTypeSerializer typeSerializer, T existingInstance) in c:\Development\GitHub\MonoGame\MonoGame.Framework.Content.Pipeline\Serialization\Intermediate\IntermediateReader.cs:line 82
at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.IntermediateReader.ReadObject[T](ContentSerializerAttribute format) in c:\Development\GitHub\MonoGame\MonoGame.Framework.Content.Pipeline\Serialization\Intermediate\IntermediateReader.cs:line 42
at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.IntermediateSerializer.Deserialize[T](XmlReader input, String referenceRelocationPath) in c:\Development\GitHub\MonoGame\MonoGame.Framework.Content.Pipeline\Serialization\Intermediate\IntermediateSerializer.cs:line 80
at MonoGame.Tests.ContentPipeline.IntermediateDeserializerTest.Deserialize[T](String file, Action`1 doAsserts) in c:\Development\GitHub\MonoGame\Test\ContentPipeline\IntermediateDeserializerTest.cs:line 70
at MonoGame.Tests.ContentPipeline.IntermediateDeserializerTest.DeserializeCompileAndLoad[T](String file, Action`1 doAsserts) in c:\Development\GitHub\MonoGame\Test\ContentPipeline\IntermediateDeserializerTest.cs:line 82
at MonoGame.Tests.ContentPipeline.IntermediateDeserializerTest.MathTypes() in c:\Development\GitHub\MonoGame\Test\ContentPipeline\IntermediateDeserializerTest.cs:line 251

**Comment by DDReaper** [comment]
FYI, uploaded my new test cases, xml and MathTypes def to my fork
https://github.com/DDReaper/MonoGame/tree/XMLVectorParsingTests

Adds test and data for a single line list test and a multiple line list test

Left the line separated XML test commented out so the test currently passes

**Comment by tgjones** [comment]
I am putting together a PR for this now.

**Comment by tomspilman** [comment]
@DDReaper - Give this a try again with the latest development build.  If you still have issues re-open this or start a new issue.

**Comment by DDReaper** [comment]
Right, will give it a run today

**Comment by DDReaper** [comment]
OK, that fix has resolved Issue 1 and line separated XML is now imported correctly.

However Issue 2 still exists:
Here's the example:
Take the following Class:
```csharp
    public class UnitAttributes
    {
        [ContentSerializer(ElementName="UnitName")]
        private string _sUnitName;

        [ContentSerializer(ElementName = "TechLevel")]
        private int _iTechLevel;
        
        [ContentSerializer(ElementName="Speed")]
        private float _fSpeed;

        [ContentSerializer(ElementName = "AirUnit")]
        private bool _bAirUnit;

        [ContentSerializer(ElementName = "AnimationDimensions")]
        private Vector2 _AnimationDimensions;

        [ContentSerializerIgnore]
        private Texture2D _UnitTexture;
}
```
With the following XML:
```xml
<?xml version="1.0" encoding="utf-8" ?>
<XnaContent>
  <Asset Type="ReturnToZero.Units.UnitAttributes">
    <UnitName>Helo</UnitName>
    <TechLevel>1</TechLevel>
    <Speed>80</Speed>
    <AirUnit>true</AirUnit>
    <AnimationDimensions>32 32</AnimationDimensions>
</Asset>
</XnaContent>
```
Now the base types seem to deserialise correctly (or at least they are not showing errors in the Build output.
However the AnimationDimensions property still causes the following error:
> C:/Development/Lushington/MGLushingtonSprings/Content/Units/unitHelo.xml: error: Importer 'XmlImporter' had unexpected failure!
Microsoft.Xna.Framework.Content.Pipeline.InvalidContentException: The Xml element `AnimationDimensions` is required!
   at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.ReflectiveSerializer.Deserialize(IntermediateReader input, ContentSerializerAttribute format, Object existingInstance)
   at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.IntermediateReader.ReadRawObject[T](ContentSerializerAttribute format, ContentTypeSerializer typeSerializer, T existingInstance)
   at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.IntermediateReader.ReadObject[T](ContentSerializerAttribute format, ContentTypeSerializer typeSerializer, T existingInstance)
   at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.IntermediateReader.ReadObject[T](ContentSerializerAttribute format)
   at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.IntermediateSerializer.Deserialize[T](XmlReader input, String referenceRelocationPath)
   at Microsoft.Xna.Framework.Content.Pipeline.XmlImporter.Import(String filename, ContentImporterContext context)
   at Microsoft.Xna.Framework.Content.Pipeline.ContentImporter`1.Microsoft.Xna.Framework.Content.Pipeline.IContentImporter.Import(String filename, ContentImporterContext context)
   at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent(PipelineBuildEvent pipelineEvent)C:/Development/Lushington/MGLushingtonSprings/Content/Towers/Missile/lvl1Missile.xml


Should this be logged as a separate issue or a continuation of the same?

**Comment by DDReaper** [comment]
OK, so continuing testing, I expanded the test case for renaming attributes to include more data types and pushed the update here:
https://github.com/DDReaper/MonoGame/tree/XMLAttributeCouldNotBeFoundError

What is annoying is that the Deserialise test still works, even with the above property on the class.

Although it turn up a new issue in the Serialise case, as that is now failing, seemingly not putting a CR on the end of the line?

Continuing testing so see if I can get this thing to break outside the tool.
Is there another way to test the MGCB from source (guessing I'll need to use the Windows Project and give it a commandline parameter to run)

**Comment by DDReaper** [comment]
OK, found the issue and it is an odd one.

Even though there is a private definition of
        [ContentSerializer(ElementName = "AnimationDimensions")]
        private Vector2 _AnimationDimensions;
It is still reflecting and also reading :
        public Vector2 AnimationDimensions
        {
            get { return _AnimationDimensions; }
        }

It get's weirder as it also reads another public fields but NOT others? 
It reflects and tries to read "TextureOrigin" but it does not reflect and read "IsOrganic" (which uses the corresponding "Organic" field in the XML for example

I've managed to work around it by adding [ContentSerializerIgnore] to the two public properties it is reading but I am a loss as to how it is happening in the first place.  

Reflection issue for serialisation??

**Comment by DDReaper** [comment]
Right, updated the "Renaming XML Elements" test case with the deserialisation error here:
https://github.com/DDReaper/MonoGame/tree/XMLAttributeCouldNotBeFoundError

So now both the Serialsation and Deserialisation tests for that XML are currently failing for different reasons.

**Comment by tgjones** [comment]
I think you might have added a newline at the end of `05_RenamingXmlElements.xml`? At least that's what GitHub's diff says. If so, that would cause the serialization test to fail - it does an exact string match, so whitespace is significant. (On that note, I notice a number of minor whitespace changes in `AssetTestClasses.cs` and `IntermediateDeserializerTest.cs`, which makes diffing harder than it needs to be - I removed a few of those when I merged your commit into my last PR, but if it's possible to remove them at source that would be even easier :).)

``` csharp
[ContentSerializer(ElementName = "AnimationDimensions")]
private Vector2 _AnimationDimensions;

public Vector2 AnimationDimensions
{
    get { return _AnimationDimensions; }
}
```

That's an interesting edge case, and definitely not one I thought about when working on the serializer (I would have expected XNA would require you to put `[ContentSerializerIgnore]` on the property to disambiguate it, but if it works in XNA, we should obviously match that). It will be nice to have a test for that, to see what XNA does - I wonder if it reads the field or the property. Maybe we can artifically make the property return something slightly different, to confirm what's happening.

**Comment by DDReaper** [comment]
Well what baffles me is this:

The AnimationDimensions and TextureOrigin public getters get picked up by the reflection logic

However the TextureFilename does not.  And apart from the data type, they are practically identical.  Caused me over 2 hours of head scratching and debigging to get this far.

**Comment by tgjones** [comment]
It's probably the data type making the difference - I think I saw a check in there which ignores get-only properties *but only if they're in the System namespace*. I'll investigate more tomorrow.

**Comment by DDReaper** [comment]
@tgjones did you make any progress on the second issue?

**Comment by tgjones** [comment]
I've rather gone down a rabbit hole with this. @DDReaper, I've fixed your issue, but I've also found a number of missing bits around getter-only properties and generic polymorphic types. I'll hopefully submit a PR tomorrow.

**Comment by DDReaper** [comment]
Fantastic it's (hopefully), the last content issue for a project I'm porting.

**Comment by DDReaper** [comment]
Thanks @tgjones missed the fix.
Just retested and ..... it's better
Now it's brought 2 new errors :dancer: 
mapCanyons.xml: error: Importer 'XmlImporter' had unexpected failure!
System.ArgumentException: An item with the same key has already been added.
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.IntermediateReader.ReadSharedResources()
   at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.IntermediateSerializer.Deserialize[T](XmlReader input, String referenceRelocationPath)
   at Microsoft.Xna.Framework.Content.Pipeline.XmlImporter.Import(String filename, ContentImporterContext context)
   at Microsoft.Xna.Framework.Content.Pipeline.ContentImporter`1.Microsoft.Xna.Framework.Content.Pipeline.IContentImporter.Import(String filename, ContentImporterContext context)
   at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent(PipelineBuildEvent pipelineEvent)C:/Development/Lushington/MGLushingtonSprings/Content/Maps/mapForest.xml

mapForest.xml: error: Importer 'XmlImporter' had unexpected failure!
Microsoft.Xna.Framework.Content.Pipeline.InvalidContentException: Not have enough entries in space-separated list!
   at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.ElementSerializer`1.Deserialize(IntermediateReader input, List`1 results)
   at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.ListSerializer`1.Deserialize(IntermediateReader input, ContentSerializerAttribute format, List`1 existingInstance)
   at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.ContentTypeSerializer`1.Deserialize(IntermediateReader input, ContentSerializerAttribute format, Object existingInstance)
   at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.IntermediateReader.ReadRawObject[T](ContentSerializerAttribute format, ContentTypeSerializer typeSerializer, T existingInstance)
   at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.IntermediateReader.ReadObject[T](ContentSerializerAttribute format, ContentTypeSerializer typeSerializer, T existingInstance)
   at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.ReflectiveSerializer.Deserialize(IntermediateReader input, ContentSerializerAttribute format, Object existingInstance)
   at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.IntermediateReader.ReadRawObject[T](ContentSerializerAttribute format, ContentTypeSerializer typeSerializer, T existingInstance)
   at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.IntermediateReader.ReadObject[T](ContentSerializerAttribute format, ContentTypeSerializer typeSerializer, T existingInstance)
   at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.IntermediateReader.ReadObject[T](ContentSerializerAttribute format)
   at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.IntermediateSerializer.Deserialize[T](XmlReader input, String referenceRelocationPath)
   at Microsoft.Xna.Framework.Content.Pipeline.XmlImporter.Import(String filename, ContentImporterContext context)
   at Microsoft.Xna.Framework.Content.Pipeline.ContentImporter`1.Microsoft.Xna.Framework.Content.Pipeline.IContentImporter.Import(String filename, ContentImporterContext context)
   at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent(PipelineBuildEvent pipelineEvent)C:/Development/Lushington/MGLushingtonSprings/Content/Towers/MG/lvl1MachineGunner.xml
I suspect both are related, do you need the code and XML for this one as well?

**Comment by tgjones** [comment]
Yes, code and XML please :)

**Comment by DDReaper** [comment]
I just knew you were going to say that.
code
https://www.dropbox.com/s/cozklwd1vfsvl8l/Map.cs?dl=0
and XML
https://www.dropbox.com/s/hj5c7j6c1p07hdy/mapForest.xml?dl=0

Files were too large to just paste here.
I did notice an extra blank line in the XML, i wonder if that could be causing it if the importer is not testing for blank space

**Comment by tgjones** [comment]
Woah - those files are kind of big! Any chance you can cut them down to a minimal failing example? Then I'll be happy to put together a fix.

**Comment by DDReaper** [comment]
OK, I've uploaded some cut down versions and verified they are still causing an error

**Comment by tgjones** [comment]
@DDReaper Hopefully #3533 fixes your issues. Let me know how you get on.

(A request for next time: please could the minimal example be a little more minimal ;-) It took me a while to trim your example down to the point where I could see what I was going on. Also the `Node` class was missing, so I took a guess at what it looked like.)

**Comment by DDReaper** [comment]
Right, checking it out now :dancer:
