### ISSUE TITLE
Error importing .tga image files

### ISSUE THREAD

**Issue by DDReaper** [mono/MonoGame#3530]
Are TGA files supported with Content Builder projects?

Getting the following error when trying to import one:

texLight.tga: error: Importer 'TextureImporter' had unexpected failure!
System.ArgumentNullException: Value cannot be null.
Parameter name: dib
   at FreeImageAPI.FreeImage.GetInfoHeaderEx(FIBITMAP dib)
   at Microsoft.Xna.Framework.Content.Pipeline.TextureImporter.Import(String filename, ContentImporterContext context)
   at Microsoft.Xna.Framework.Content.Pipeline.ContentImporter`1.Microsoft.Xna.Framework.Content.Pipeline.IContentImporter.Import(String filename, ContentImporterContext context)
   at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent(PipelineBuildEvent pipelineEvent)Skipping C:/Development/Lushington/MGLushingtonSprings/Content/Textures/UI/Images/texTitle.dds

**Comment by tomspilman** [comment]
> Are TGA files supported with Content Builder projects?

Yes... they should be supported.

**Comment by tgjones** [comment]
I just downloaded a random `.tga` file off the internet, and got the same exception.

I notice that MG's version of FreeImageNET.dll is a little old - 3.15.1.0 - where the current version is 3.16.0.0. Maybe this bug has been fixed?

I tried to build a new version, but it's a bit involved - there doesn't seem to be a binary download for the x64 native DLL.

**Comment by DDReaper** [comment]
Thanks for confirming that @tgjones , not just me then :dancer:

**Comment by tomspilman** [comment]
Could be we are just using the API wrong for TGAs.   Someone needs to investigate it.

**Comment by DDReaper** [comment]
Right, did some investigation and it seems the library we use for all images is FreeImage.  Acordinh to the support logs, TGA support was added in to the latest version 3.16 (which we are using) back in early 2014.

So FreeImage does support it, however looking in:
```csharp
    public class TextureImporter : ContentImporter<TextureContent>
```
It looks like we are only using it in a basic fashion to load every image type as a bitmap (unless I'm reading the docs and comments wrong)

So from what I can gather, this area needs some serious effort to sort out all the supported image types (probably with a lot of unit tests) and implement them correctly instead of the basic import it is using now.

Either that or simply state MG only supports formats directly convertible to bitmaps?

Thoughts @tomspilman @KonajuGames ?
P.S. Sent a mail asking how to write unit tests for mgcb?

**Comment by KonajuGames** [comment]
FreeImage has different ways of loading different file types?  TGA is a
simple image format that is easily converted to a bitmap.  I haven't read
the FreeImage docs, but it is something that should not be overly complex.​

**Comment by DDReaper** [comment]
Looking at the sample you can either use the 
```csharp
FreeImage.LoadEx(filename);
```
or the more specific 
```csharp
FreeImage.Load(FREE_IMAGE_FORMAT.FIF_JPEG, fileName, FREE_IMAGE_LOAD_FLAGS.JPEG_ACCURATE);
```

Whether or not this has a direct impact, I'm not sure.  But sure enough .tga files do not load currently, also not sure if all the formats listed in the TextureImporter class do actually load?

**Comment by tomspilman** [comment]
We certainly have not tested all the possible formats.

But first of all...  we really should avoid developing a test to test FreeImage itself.  It is the FreeImage's teams job to test FreeImage.  I worry that we can get crazy elaborate here and just waste our time and efforts.

Where does this leave us?  Not sure.  We need a test that tests MonoGame's `TextureImporter` uses FreeImage correctly and it results in the same `TextureContent` as XNA, but nothing much deeper really.

**Comment by DDReaper** [comment]
I think Tom we should start with building UnitTests to check the TextureImporter for each of the file types listed.
I've started working on a PR but asking for advise as how best to write UnitTests for the TextureProcessor of MCGB

**Comment by tomspilman** [comment]
> UnitTests to check the TextureImporter for each of the file types listed.

Note this means 100s of files to test.  Each format has variations... with alpha, without alpha, greyscale, different bit depths, interlacing, etc.  PNG alone has over 100 different sub-formats (see http://www.schaik.com/pngsuite/).

Not to mention the possibly 100s of comparision images you need to verify the import worked.

I really don't look forward to adding 100s of MBs of images for tests to the github repo either.

This is all why I warn again against this path of re-testing FreeImage features.


> how best to write UnitTests for the TextureProcessor of MCGB

Reminder... this isn't about writing tests for the `TextureProcessor`.  This is about writing tests that the `TextureImporter` works.  The tests for each are independent.

If multiple files are involved you want to write `TestCase` attributes like the stock effect tests do:

https://github.com/mono/MonoGame/blob/develop/Test/ContentPipeline/EffectProcessorTests.cs#L56

You can see here how easy it is to fire off an importer via code:

https://github.com/mono/MonoGame/blob/develop/Test/ContentPipeline/EffectProcessorTests.cs#L65

It even works under XNA... speaking of you may need to `#if !XNA` some tests when testing features that don't run under XNA.

**Comment by DDReaper** [comment]
I'd agree @tomspilman 
Let's start small, work a plan and then see how to push it forward. baby steps.

So first look at the common image types (png, jpg, tga, dds, gif) and check the processors work as expected.  Then plan how to improve the process going forward.

I agree this shouldn't be a test of FreeImage, more a test of our implementation of FreeImage and whether it is:
A: the right tool for the job
B: if we are using it correctly for the best quality

> Reminder... this isn't about writing tests for the TextureProcessor. This is about writing tests that the TextureImporter works. The tests for each are independent.

Understand the distinction now and I think you are right.

I'll check out those examples and see what I can come up with.

**Comment by SimonDarksideJ** [comment]
I cannot replicate this issue on the latest 3.8.4.1 release, so I am closing this issue. Please reopen if it is still and issue
