### ISSUE TITLE
Assimp64.so missing / incorrect name 

### ISSUE THREAD

**Issue by chriscamacho** [mono/MonoGame#3599]
I get this error when trying to convert an fbx

`Build started 08/03/2015 22:13:14

/home/chris/development/monogame/MonoGameTest/MonoGameTest/Content/cube.fbx
/home/chris/development/monogame/MonoGameTest/MonoGameTest/Content/cube.fbx: error: Importer 'FbxImporter' had unexpected failure!
Assimp.AssimpException: Error loading unmanaged library from path: Assimp64.so, error detail:
Assimp64.so: cannot open shared object file: No such file or directory
  at Assimp.Unmanaged.AssimpLibraryLinuxImplementation.NativeLoadLibrary (System.String path) [0x00000] in <filename unknown>:0 
  at Assimp.Unmanaged.AssimpLibraryImplementation.LoadAssimpLibrary (System.String path) [0x00000] in <filename unknown>:0 
  at Assimp.Unmanaged.AssimpLibrary.LoadLibrary () [0x00000] in <filename unknown>:0 
  at Assimp.Unmanaged.AssimpLibrary.LoadIfNotLoaded () [0x00000] in <filename unknown>:0 
  at Assimp.Unmanaged.AssimpLibrary.CreatePropertyStore () [0x00000] in <filename unknown>:0 
  at Assimp.AssimpContext.CreateConfigs () [0x00000] in <filename unknown>:0 
  at Assimp.AssimpContext.PrepareImport () [0x00000] in <filename unknown>:0 
  at Assimp.AssimpContext.ImportFile (System.String file, PostProcessSteps postProcessFlags) [0x00000] in <filename unknown>:0 
  at Microsoft.Xna.Framework.Content.Pipeline.OpenAssetImporter.Import (System.String filename, Microsoft.Xna.Framework.Content.Pipeline.ContentImporterContext context) [0x00000] in <filename unknown>:0 
  at Microsoft.Xna.Framework.Content.Pipeline.FbxImporter.Import (System.String filename, Microsoft.Xna.Framework.Content.Pipeline.ContentImporterContext context) [0x00000] in <filename unknown>:0 
  at Microsoft.Xna.Framework.Content.Pipeline.ContentImporter`1[Microsoft.Xna.Framework.Content.Pipeline.Graphics.NodeContent].Microsoft.Xna.Framework.Content.Pipeline.IContentImporter.Import (System.String filename, Microsoft.Xna.Framework.Content.Pipeline.ContentImporterContext context) [0x00000] in <filename unknown>:0 
  at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent (MonoGame.Framework.Content.Pipeline.Builder.PipelineBuildEvent pipelineEvent) [0x00000] in <filename unknown>:0 
Build 0 succeeded, 1 failed.

Time elapsed 00:00:00.134.`

if I mention in AssimpNet.dll.config libassimp.so I get an unhandled exception (or symlink it)
`mono --debug Pipeline.exe 
Exception in Gtk# callback delegate
  Note: Applications can use GLib.ExceptionManager.UnhandledException to handle the exception.
System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
  at System.Collections.Generic.List`1+Enumerator[System.String].MoveNext () [0x00075] in /var/tmp/portage/dev-lang/mono-3.2.8/work/mono-3.2.8/mcs/class/corlib/System.Collections.Generic/List.cs:818 
  at MonoGame.Tools.Pipeline.MainWindow.UpdateRecentProjectList () [0x00000] in <filename unknown>:0 
  at MonoGame.Tools.Pipeline.MainWindow.UpdateMenus () [0x00000] in <filename unknown>:0 
  at MonoGame.Tools.Pipeline.MainWindow+<OutputAppend>c__AnonStorey0.<>m__0 (System.Object , System.EventArgs ) [0x00000] in <filename unknown>:0 
  at Gtk.Application+InvokeCB.Invoke () [0x00000] in <filename unknown>:0 
  at GLib.Timeout+TimeoutProxy.Handler () [0x00000] in <filename unknown>:0 
   at GLib.ExceptionManager.RaiseUnhandledException(System.Exception e, Boolean is_terminal)
   at GLib.Timeout+TimeoutProxy.Handler()
   at Gtk.Application.gtk_main()
   at Gtk.Application.Run()
   at MonoGame.Tools.Pipeline.Program.Main(System.String[] args)
`

**Comment by cra0zy** [comment]
Long story short, you'll need libstdc++6 that supports GLIBCXX_3.4.20. If you are on Ubuntu do the following:
> sudo add-apt-repository ppa:ubuntu-toolchain-r/test 
> sudo apt-get update
> sudo apt-get install libstdc++6

**Comment by cra0zy** [comment]
PS. If you want to check if you have libstdc++6 that supports GLIBCXX_3.4.20, type in:
> strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX

**Comment by chriscamacho** [comment]
I'm on Gentoo there is a compatability package for Virtual for the GNU Standard C++ Library for <gcc-3.4

my compiler is gcc (Gentoo 4.8.3 p1.1, pie-0.5.9) 4.8.3

strings /usr/lib64/gcc/x86_64-pc-linux-gnu/4.8.3/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2 <--- ???
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_DEBUG_MESSAGE_LENGTH

**Comment by cra0zy** [comment]
3.4.2 is not 3.4.20

**Comment by chriscamacho** [comment]
Duh! let me see if its masked as beta... I'll return here if I can get it working or not!

**Comment by chriscamacho** [comment]
seems there is no compiler available on gentoo to support this
gcc (Gentoo 4.8.3 p1.1, pie-0.5.9) 4.8.3 (most uptodate gcc for gentoo - (accepting ~amd (unstable) keyword)) still gives the same strings for strings /usr/lib64/gcc/x86_64-pc-linux-gnu/4.8.3/libstdc++.so.6 | grep GLIBCXX
GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19


I had a look at compiling assimpNet against the C assimp library available as a native library on gentoo (version 3.1.1) but couldn't seem to get the solution file for assimpNet to import into MonoDevelop

**Comment by cra0zy** [comment]
So I have a solution for you. You can replace your libstc++6 lib with this one: https://mega.co.nz/#!aQZUmbhR!d4ePyTXvyVNfezQ_Njo70hfksyrcH5kjR2v20i6aEBU
I tested doing this in vm and it did allow me to compile fbx files.

**Comment by chriscamacho** [comment]
yeah right - and where did that come from ? 

I'd rather create my own libs especially core ones... - I've spend too much time on this already

**Comment by cra0zy** [comment]
it is extracted from ppa:ubuntu-toolchain-r/test which comes from https://wiki.ubuntu.com/ToolChain

**Comment by chriscamacho** [comment]
That's just gonna get stomped on next time I update... I'm not having random bit from other distro's floating about just to support a single file converter... you might see this as a solution - I don't

**Comment by danzel** [comment]
Is the issue that our ```Assimp64.so``` is built against a version of glibcxx that is newer than gentoo includes/supports?
Can we statically link it or something?

**Comment by cra0zy** [comment]
@danzel We have the same idea: https://github.com/Mono-Game/MonoGame.Dependencies/pull/46

**Comment by danzel** [comment]
:+1:

**Comment by cra0zy** [comment]
Ubuntu 15.04 comes with libstc++6 thats new enough,
