### ISSUE TITLE
[Pipeline,WIN] error: Importer 'XmlImporter' had unexpected failure!

### ISSUE THREAD

**Issue by mort8088** [mono/MonoGame#3668]
I imported my old XNA "DodgeContent.contentproj" file and had an exception when building.

Settings >>>
Build Action - Build
Importer - Xml Importer - MonoGame
Processor - No Processing Required

File Content >>>

`<?xml version="1.0" encoding="utf-8" ?>`
`<XnaContent>`
`    <Asset Type="System.Collections.Generic.Dictionary[System.String, Microsoft.Xna.Framework.Rectangle]">`
`        <Item><Key>background</Key><Value>0 0 320 200</Value></Item>`
`        <Item><Key>Info</Key><Value>0 201 320 200</Value></Item>`
`        <Item><Key>Warp</Key><Value>321 0 96 32</Value></Item>`
`        <Item><Key>Center</Key><Value>321 33 32 32</Value></Item>`
`        <Item><Key>disabled</Key><Value>321 66 32 32</Value></Item>`
`        <Item><Key>Down</Key><Value>354 33 32 32</Value></Item>`
`        <Item><Key>DownLeft</Key><Value>0 402 32 32</Value></Item>`
`        <Item><Key>DownRight</Key><Value>418 0 32 32</Value></Item>`
`        <Item><Key>enabled</Key><Value>354 66 32 32</Value></Item>`
`        <Item><Key>gradient</Key><Value>387 33 32 32</Value></Item>`
`        <Item><Key>Left</Key><Value>321 99 32 32</Value></Item>`
`        <Item><Key>Right</Key><Value>0 435 32 32</Value></Item>`
`        <Item><Key>Up</Key><Value>33 402 32 32</Value></Item>`
`        <Item><Key>UpLeft</Key><Value>451 0 32 32</Value></Item>`
`        <Item><Key>UpRight</Key><Value>321 132 32 32</Value></Item>`
`        <Item><Key>teleport</Key><Value>420 33 24 24</Value></Item>`
`        <Item><Key>dude</Key><Value>387 66 16 16</Value></Item>`
`        <Item><Key>empty</Key><Value>354 99 16 16</Value></Item>`
`        <Item><Key>mine</Key><Value>33 435 16 16</Value></Item>`
`        <Item><Key>player</Key><Value>0 468 16 16</Value></Item>`
`        <Item><Key>tank</Key><Value>66 402 16 16</Value></Item>`
`    </Asset>`
`</XnaContent>`

Exception from build log >>>
D:/CODE/MonoGame/Dodge/DodgeContent/Textures/Dodge_map.xml: error: Importer 'XmlImporter' had unexpected failure!
System.ArgumentNullException: Value cannot be null.
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.IntermediateSerializer.FindType(String typeName)
   at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.IntermediateReader.ReadObject[T](ContentSerializerAttribute format, ContentTypeSerializer typeSerializer, T existingInstance)
   at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.IntermediateReader.ReadObject[T](ContentSerializerAttribute format)
   at Microsoft.Xna.Framework.Content.Pipeline.Serialization.Intermediate.IntermediateSerializer.Deserialize[T](XmlReader input, String referenceRelocationPath)
   at Microsoft.Xna.Framework.Content.Pipeline.XmlImporter.Import(String filename, ContentImporterContext context)
   at Microsoft.Xna.Framework.Content.Pipeline.ContentImporter`1.Microsoft.Xna.Framework.Content.Pipeline.IContentImporter.Import(String filename, ContentImporterContext context)
   at MonoGame.Framework.Content.Pipeline.Builder.PipelineManager.ProcessContent(PipelineBuildEvent pipelineEvent)

**Comment by tomspilman** [comment]
We need someone to debug this one, modify one of the existing unit tests to make it exhibit the same bug, then write a fix for it.

**Comment by tgjones** [comment]
I'd forgotten about this one - I'll push up a fix now. The only problem here was the space in the generic type:

``` xml
<Asset Type="System.Collections.Generic.Dictionary[System.String, Microsoft.Xna.Framework.Rectangle]">
```

We weren't trimming the generic argument strings, so the type lookup failed.

**Comment by tomspilman** [comment]
Oh... so very simple.  I guess we didn't have any unit test that had that case.
