### ISSUE TITLE
GamePad throws Exception in Windows 10 UAP projects on phones

### ISSUE THREAD

**Issue by jakepoz** [mono/MonoGame#3819]
Using the new Windows 10 UAP templates, there an exception is thrown when using the GamePad API.

This happens only when running the app on a Windows 10 Phone (emulator in this case), not when running on a desktop PC.

```C#
bool isBackButtonPressed = GamePad.GetState(PlayerIndex.One).Buttons.Back == ButtonState.Pressed;
-----------
{System.DllNotFoundException: Unable to load DLL 'xinput1_4.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at SharpDX.XInput.XInput.XInputGetState_(Int32 arg0, Void* arg1)
   at SharpDX.XInput.XInput.XInputGetState(Int32 dwUserIndex, State& stateRef)
   at SharpDX.XInput.XInput14.XInputGetState(Int32 dwUserIndex, State& stateRef)
   at Microsoft.Xna.Framework.Input.GamePad.PlatformGetState(Int32 index, GamePadDeadZone deadZoneMode)
   at Microsoft.Xna.Framework.Input.GamePad.GetState(PlayerIndex playerIndex, GamePadDeadZone deadZoneMode)
   at Microsoft.Xna.Framework.Input.GamePad.GetState(PlayerIndex playerIndex)
   at Salad.SaladGame.Update(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.DoUpdate(GameTime gameTime)
   at Microsoft.Xna.Framework.Game.Tick()
   at Microsoft.Xna.Framework.UAPGameWindow.Tick()
   at Microsoft.Xna.Framework.UAPGamePlatform.<>c.<StartRunLoop>b__10_0(Object o, Object a)}``

**Comment by tomspilman** [comment]
I was talking to @KonajuGames about this the other day.  I think for now we need to handle this exception and return an empty state.  I can setup a PR for that later today.

I know there will be a new gamepad API in the coming months that will replace XInput soon. I suspect that one will work on all the platforms including WP.

**Comment by jakepoz** [comment]
Thanks Tom,

 What would be the proper way to capture the back button state on this platform then?

**Comment by tomspilman** [comment]
Not sure... i'll investigate that while i'm at it.

**Comment by KonajuGames** [comment]
I wrapped the game side call to GetState in a try..catch for my simple
demo.​

**Comment by jamesford42** [comment]
Why are we catching this? If you need a dll in order to get the gamepad state, and you are trying to get the gamepad state, and can't because a dll is missing, that seems like an exception worthy situation.

**Comment by tomspilman** [comment]
> Why are we catching this?

That is a good question.  I don't remember exactly what I was thinking at the time, but I suppose I thought that not having the correct version XInput dll installed should not be a fatal issue.

If your game supports multiple input systems (touch, keyboard, gamepad, etc) then yea... this might not need to be fatal.  If your game only supports gamepad then maybe it should be.

Ideally we wouldn't just throw on startup... as if the game/player never uses the gamepad then it should be a fatal issue.

Also for the developer we wouldn't just let a DirectX exception of some sort bubble up to them.  Ideally we would wrap it into some MonoGame/XNA exception that lets them decide if they want to bother the user, ignore it, or crash out.

@dellis1972  @KonajuGames ?
