### ISSUE TITLE
Drawing With Disposed Resources

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#3890]
So I did this test tonight on an XNA desktop game:

```
        private BasicEffect _effect;
        private VertexBuffer _vb;
        private IndexBuffer _ib;

        protected override void Draw(GameTime gameTime)
        {
            GraphicsDevice.Clear(Color.CornflowerBlue);

            if (_effect == null)
                _effect = new BasicEffect(GraphicsDevice);

            _effect.CurrentTechnique.Passes[0].Apply();

            if (_vb == null)
            {
                _vb = new VertexBuffer(GraphicsDevice, VertexPositionColor.VertexDeclaration, 4, BufferUsage.WriteOnly);
                _vb.SetData( new [] {
                    new VertexPositionColor(Vector3.Zero, Color.White),
                    new VertexPositionColor(Vector3.Zero, Color.White),
                    new VertexPositionColor(Vector3.Zero, Color.White),
                    new VertexPositionColor(Vector3.Zero, Color.White),
                });
                GraphicsDevice.SetVertexBuffer(_vb);
                _vb.Dispose();
            }

            GraphicsDevice.DrawPrimitives(PrimitiveType.TriangleList, 0, 2);

            if (_ib == null)
            {
                _ib = new IndexBuffer(GraphicsDevice, IndexElementSize.SixteenBits, 6, BufferUsage.WriteOnly);
                _ib.SetData(new short[] {0, 1, 2, 2, 3, 0});
                GraphicsDevice.Indices = _ib;
                _ib.Dispose();
            }

            GraphicsDevice.DrawIndexedPrimitives(PrimitiveType.TriangleList, 0, 0, 4, 0, 2);

            base.Draw(gameTime);
        }
```

I did this test fully expecting XNA to throw some helpful exceptions saying the VB and IB were disposed.  I was then going to write this issue saying we need to implement the same checks and exceptions in MonoGame.

BUT

XNA does not throw any exceptions or errors in this case.  In fact it happily draws nothing to the screen... doesn't matter how long it runs.

So first issue....  did I miss something in my test here?

Second issue...  although XNA doesn't throw exceptions in this case, should we fix MonoGame to protect against these mistakes?

**Comment by tomspilman** [comment]
So if I change the code above to do this:
```
    if (_vb == null)
    {
        _vb = new VertexBuffer(GraphicsDevice, VertexPositionColor.VertexDeclaration, 4, BufferUsage.WriteOnly);
        _vb.SetData( new [] {
            new VertexPositionColor(Vector3.Zero, Color.White),
            new VertexPositionColor(Vector3.Zero, Color.White),
            new VertexPositionColor(Vector3.Zero, Color.White),
            new VertexPositionColor(Vector3.Zero, Color.White),
        });
        _vb.Dispose();
    }

    GraphicsDevice.SetVertexBuffer(_vb);
    GraphicsDevice.DrawPrimitives(PrimitiveType.TriangleList, 0, 2);
```
I get an exception:

```
System.ObjectDisposedException was unhandled
  HResult=-2146232798
  Message=Cannot access a disposed object.
Object name: 'VertexBuffer'.
  Source=Microsoft.Xna.Framework
  ObjectName=VertexBuffer
  StackTrace:
       at Microsoft.Xna.Framework.Helpers.CheckDisposed(Object obj, IntPtr pComPtr)
       at Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetVertexBuffers(VertexBufferBinding* pBindings, Int32 vertexBufferCount)
       at Microsoft.Xna.Framework.Graphics.GraphicsDevice.SetVertexBuffer(VertexBuffer vertexBuffer)
       at WindowsGame2.Game1.Draw(GameTime gameTime) in D:\Projects\junk\WindowsGame2\WindowsGame2\WindowsGame2\Game1.cs:line 103
       at Microsoft.Xna.Framework.Game.DrawFrame()
       at Microsoft.Xna.Framework.Game.Tick()
       at Microsoft.Xna.Framework.Game.HostIdle(Object sender, EventArgs e)
       at Microsoft.Xna.Framework.GameHost.OnIdle()
       at Microsoft.Xna.Framework.WindowsGameHost.RunOneFrame()
       at Microsoft.Xna.Framework.WindowsGameHost.ApplicationIdle(Object sender, EventArgs e)
       at System.Windows.Forms.Application.ThreadContext.System.Windows.Forms.UnsafeNativeMethods.IMsoComponent.FDoIdle(Int32 grfidlef)
       at System.Windows.Forms.Application.ComponentManager.System.Windows.Forms.UnsafeNativeMethods.IMsoComponentManager.FPushMessageLoop(IntPtr dwComponentID, Int32 reason, Int32 pvLoopData)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoopInner(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.ThreadContext.RunMessageLoop(Int32 reason, ApplicationContext context)
       at System.Windows.Forms.Application.Run(Form mainForm)
       at Microsoft.Xna.Framework.WindowsGameHost.Run()
       at Microsoft.Xna.Framework.Game.RunGame(Boolean useBlockingRun)
       at Microsoft.Xna.Framework.Game.Run()
       at WindowsGame2.Program.Main(String[] args) in D:\Projects\junk\WindowsGame2\WindowsGame2\WindowsGame2\Program.cs:line 15
  InnerException: 
```
I suspect for sure MonoGame isn't checking for this case.

**Comment by tomspilman** [comment]
@tgjones @dellis1972 @Nezz - Thoughts?

**Comment by dellis1972** [comment]
personally, I think it you dispose something it should be gone... the fact that this worked in XNA seems like a bug in XNA :P

**Comment by KonajuGames** [comment]
Systems such as consoles use command buffers that hold references to resources.  These command buffers may exists for one or two frames after being submitted.  If you release the resource while a command buffer has a reference to it, you run the risk of crashing the GPU.

**Comment by tomspilman** [comment]
> If you release the resource while a command buffer has a reference to it, you run the risk of crashing the GPU.

Right...  this is true and is valid for us to do at the platform layer.

Still at the user code level...  they shouldn't be allowed to call any Draw method with a disposed resource.

**Comment by willmotil** [comment]
I just noticed this was in the help wanted area
I dunno if you guys fully resolve this but. 
i figured for posterity i would drop in some input here.

I actually had a little discussion with shawn hargreaves about this in a related way.

To make a long long story short .... This was my solution later to a related problem.

Draw then tell the gpu that the vb and ib arrays are zero in size 
Then dispose the array or null it and let the gc do it on the next collect.
That way your telling the gpu in a round about way the memory is zeroed 
The gc by dispose to free the array memory, 
but i had a array of references to the old zeroed ib vbs 
then had the arrays themselves go out of scope 
prolly not the best way but when are you really doing this other then when your maxing the memory.

something like this is sort of the gist of it.

private BasicEffect _effect;
private VertexBuffer _vb;
private IndexBuffer _ib;

protected override void Draw(GameTime gameTime)
{
    GraphicsDevice.Clear(Color.CornflowerBlue);

    if (_effect == null)
    {
        _effect = new BasicEffect(GraphicsDevice);

        var vp = GraphicsDevice.Viewport;
        Matrix projection;
        Matrix.CreateOrthographicOffCenter(0, vp.Width, vp.Height, 0, 0, 1, out projection);
        _effect.Projection = projection;
    }

   // if (_vb == null) redundant reference is already null
   // {
        _vb = new VertexBuffer(GraphicsDevice, VertexPositionColor.VertexDeclaration, 6, BufferUsage.WriteOnly);
        _vb.SetData( new [] {
            new VertexPositionColor(new Vector3(100, 100, 0), Color.White),
            new VertexPositionColor(new Vector3(200, 100, 0), Color.White),
            new VertexPositionColor(new Vector3(200, 200, 0), Color.White),
            new VertexPositionColor(new Vector3(100, 200, 0), Color.White),
            new VertexPositionColor(new Vector3(100, 100, 0), Color.White),
            new VertexPositionColor(new Vector3(200, 200, 0), Color.White),
        });
        GraphicsDevice.SetVertexBuffer(_vb);
        // _vb.Dispose(); no not yet
   // }

    _effect.World = Matrix.Identity;
    _effect.DiffuseColor = Color.Red.ToVector3();
    _effect.CurrentTechnique.Passes[0].Apply();
    GraphicsDevice.DrawPrimitives(PrimitiveType.TriangleList, 0, 2);

    // if (_ib == null)
   // {
        _ib = new IndexBuffer(GraphicsDevice, IndexElementSize.SixteenBits, 6, BufferUsage.WriteOnly);
        _ib.SetData(new short[] {0, 1, 2, 3, 0, 2});
        GraphicsDevice.Indices = _ib;
        // _ib.Dispose(); nop not yet
    // }

    _effect.World = Matrix.CreateTranslation(0, 200, 0);
    _effect.DiffuseColor = Color.Green.ToVector3();
    _effect.CurrentTechnique.Passes[0].Apply();
    GraphicsDevice.DrawIndexedPrimitives(PrimitiveType.TriangleList, 0, 0, 4, 0, 2);

    base.Draw(gameTime);

    // now well be disposing it but you cant tell the gpu to dispose it really it will do what it wants.
    // before you dispose it tell the gpu that thier is zippo memory for this vb or ib used now.
    if (_vb ! null)
    {
       _vb = new VertexBuffer(GraphicsDevice, VertexPositionColor.VertexDeclaration, 0, BufferUsage.WriteOnly);
      _vb.SetData( new [] {} ); // not really sure if that will work but;
      _vb.Dispose();
      // this is arguably pointless might as well 
      //  _vb = null; gc.collect(); your only working on the new[] array
    }
   ... 
   // same for the index buffer
   ....
}

I was filling the gpu and virtual memory and swapping huge textures in and out so i came up with this idea of clearing the gpu memory in a round about way as well as making the method one pass for later encapsulation.
