### ISSUE TITLE
[WP8.1] MonoGame.Framework.StorageDevice throws NotSupportedException

### ISSUE THREAD

**Issue by kjpou1** [mono/MonoGame#3988]
module [MonoGame.Framework.StorageDevice](https://github.com/mono/MonoGame/blob/master/MonoGame.Framework/Storage/StorageDevice.cs)

Throws the following:

System.NotSupportedException: Specified method is not supported.
at Microsoft.Xna.Framework.Storage.ShowSelectorAsynchronousShowNoPlayer.BeginInvoke(Int32 sizeInBytes, Int32 directoryCount, AsyncCallback callback, Object object)
at Microsoft.Xna.Framework.Storage.StorageDevice.BeginShowSelector(Int32 sizeInBytes, Int32 directoryCount, AsyncCallback callback, Object state)

This happens in the BeginInvoke on the delegate.

**Comment by kjpou1** [comment]
Closed via commit https://github.com/mono/MonoGame/pull/3989
