### ISSUE TITLE
"Content reader could not be found" when nesting classes

### ISSUE THREAD

**Issue by f-aa** [mono/MonoGame#4032]
I'm trying to port my XNA game over to MonoGame, but I'm running into this error when the game is trying to load some of my classes from disk. I'll try and include as much detail as I can so this is probably going to be a bit long. I downloaded the MonoGame sources to try and debug, but I'm hitting a wall and I'm hoping someone can help me sort this out.

I have a CoolingSystem<T> class, a Weapon class and a Projectile class. T is ITemperatureModule, which Weapon inherits. CoolingSystem<T> does not have any properties of type Weapon nor T. Weapon has a public property of List<Projectile>.

I can load most my assets, but these ones aren't working properly (there are some others too, but I'm assuming they suffer from the same problem). They're all XML files in the content directory. I load them doing this:

    StoreItems.Load<CoolingSystem<Weapon>>      (@"Game\Equipment\WCS01");

There's some background stuff going on here, but it essentially calls the ContentManager Load<T>() method.

You can skip the next paragraph if you don't care about the backstory.

That puts me in the ContentManager.cs file (line 177). This all works. There's a call to ReadAsset<T>() on line 209, that all works until it calls ReadAsset<T>() on line 294. This puts me in the ContentReader.cs file on line 69. InitializeTypeReaders() is then called, and on line 83 it calls LoadAssetReaders(). This takes me to ContentTypeReaderManager.cs and line 79.

Ok, so on line 130 the reader goes and sees how many readers are in the class. In my case, it's 14. From there until line 202 it loops through a bunch of stuff to figure out which readers it needs. This is all peachy. In my case we only care about contentReaders[1] (the second one). It reports back the following type:

    {Microsoft.Xna.Framework.Content.ReflectiveReader<PewEngine.Modules.Weapons.Weapon>}

Once it's done looping through, that's where we get to my problem. On line 205 (ContentTypeReaderManager.cs in case you've lost track) it loops through all the readers to see if they need to be initialized. The one we care about does. This calls the Initialize() method on ReflectiveReader.cs. This is where it poops.

From what I can tell, this method loops through all the properties of the class passed in (PewEngine.Modules.Weapons.Weapon). The very first one of these is of type List<Projectile>. It then goes and tries to figure out the reader to use for that type (line 52). There's a bunch of code that it does for this, but it eventually ends up at the GetTypeReader() method in ContentTypeReaderManager.cs (line 59).

Notice on line 62 it tries to lookup the correct reader using the original 14 content readers it looped through in the CoolingSystem<T> class. But there is no reader for List<Projectile> in that class, so there is no reader to look up. The method returns null, which causes the code to throw an exception in ReflectiveReader.cs (line 148).

And that's where I'm stuck. I'm trying to create a sample project that exhibits the same issue, but I haven't been able to reproduce it. I was also thinking of trying to fix the issue, but I'm honestly not sure how to attack the problem. I'm going to keep plugging away at it, but I was hoping maybe someone smarter than me might be able to look at it. If additional information is needed, just let me know.

I'd rather not provide a link for the source of my game for everyone to download, but if someone needs it to troubleshoot I can provide access to it (Visual Studio Online or a ZIP package).

As a side note, in case it's not obvious, this all works fine with XNA 4.0.

![contenttypereadermanager](https://cloud.githubusercontent.com/assets/12102130/8884974/b3db5b52-3218-11e5-8265-79b894656509.PNG)
![reflectivereader](https://cloud.githubusercontent.com/assets/12102130/8884975/b3db666a-3218-11e5-9301-93b838a3c2dd.PNG)

**Comment by lllAlexlll** [comment]
Hi,

Do you use old XNA Content Project or MonoGame Content (MGCB)?
I'm asking because, for example, I have converted my XNA game to MonoGame some time ago and I still use old XNA Content Project and do not use MonoGame MGCB tool to build my content so far.

**Comment by f-aa** [comment]
Ops, that's probably pretty important information. I'm using the MonoGame one. XNA is not even installed.

Frode

Sent from my Windows Phone
________________________________

**Comment by lllAlexlll** [comment]
Hi,
Can you please show us exception call stack trace?

**Comment by f-aa** [comment]
This is the exception as it is thrown by the Content Manager:

```
   at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject) in C:\Users\frode\Source\Repos\MonoGame\MonoGame.Framework\Content\ContentManager.cs:line 321
   at Microsoft.Xna.Framework.Content.ContentManager.Load[T](String assetName) in C:\Users\frode\Source\Repos\MonoGame\MonoGame.Framework\Content\ContentManager.cs:line 209
   at Aarebrot.Common.LocalizableContentManager.LocalizableLoad[T](String assetName) in C:\Users\frode\Source\Workspaces\Common Game Library\Code\v2.0-monogame\Aarebrot.Common\Aarebrot.Common\LocalizableContentManager.cs:line 46
   at PewPew.StoreItems.Load[T](String path) in C:\Users\frode\Source\Workspaces\PewPew\Code\v1.0-monogame\PewPew\PewPew\StoreItems.cs:line 58
   at PewPew.StoreItems.PreLoadAll(LocalizableContentManager contentManager) in C:\Users\frode\Source\Workspaces\PewPew\Code\v1.0-monogame\PewPew\PewPew\StoreItems.cs:line 102
   at PewPew.Screens.MainScreen.LoadContent(SessionContext context) in C:\Users\frode\Source\Workspaces\PewPew\Code\v1.0-monogame\PewPew\PewPew\Screens\MainScreen.cs:line 52
   at Aarebrot.Common.Screen.ScreenManager.AddScreen(GameScreen screen) in C:\Users\frode\Source\Workspaces\Common Game Library\Code\v2.0-monogame\Aarebrot.Common\Aarebrot.Common\Screen\ScreenManager.cs:line 263
   at PewPew.PewPew.Initialize() in C:\Users\frode\Source\Workspaces\PewPew\Code\v1.0-monogame\PewPew\PewPew\PewPew.cs:line 76
   at Microsoft.Xna.Framework.Game.DoInitialize() in C:\Users\frode\Source\Repos\MonoGame\MonoGame.Framework\Game.cs:line 679
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior) in C:\Users\frode\Source\Repos\MonoGame\MonoGame.Framework\Game.cs:line 384
   at Microsoft.Xna.Framework.Game.Run() in C:\Users\frode\Source\Repos\MonoGame\MonoGame.Framework\Game.cs:line 370
   at PewPew.Program.Main(String[] args) in C:\Users\frode\Source\Workspaces\PewPew\Code\v1.0-monogame\PewPew\PewPew\Program.cs:line 20
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

This is the inner exception, thrown by ReflectiveReader:

```
   at Microsoft.Xna.Framework.Content.ReflectiveReader`1.GetElementReader(ContentTypeReaderManager manager, MemberInfo member) in C:\Users\frode\Source\Repos\MonoGame\MonoGame.Framework\Content\ContentReaders\ReflectiveReader.cs:line 153
   at Microsoft.Xna.Framework.Content.ReflectiveReader`1.Initialize(ContentTypeReaderManager manager) in C:\Users\frode\Source\Repos\MonoGame\MonoGame.Framework\Content\ContentReaders\ReflectiveReader.cs:line 52
   at Microsoft.Xna.Framework.Content.ContentTypeReaderManager.LoadAssetReaders(ContentReader reader) in C:\Users\frode\Source\Repos\MonoGame\MonoGame.Framework\Content\ContentTypeReaderManager.cs:line 208
   at Microsoft.Xna.Framework.Content.ContentReader.InitializeTypeReaders() in C:\Users\frode\Source\Repos\MonoGame\MonoGame.Framework\Content\ContentReader.cs:line 83
   at Microsoft.Xna.Framework.Content.ContentReader.ReadAsset[T]() in C:\Users\frode\Source\Repos\MonoGame\MonoGame.Framework\Content\ContentReader.cs:line 69
   at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject) in C:\Users\frode\Source\Repos\MonoGame\MonoGame.Framework\Content\ContentManager.cs:line 294
```

The exception is thrown because GetTypeReader() on line 147 in ReflectiveReader.cs returns null. See snippet below.

```
            var reader = manager.GetTypeReader(elementType);
            if (reader == null)
                throw new ContentLoadException(string.Format("Content reader could not be found for {0} type.", elementType.FullName));
```

In my first post the first screenshot shows the innards of this method. I pinned all the readers that are loaded in _contentReaders as well as the targetType that it's trying to find there. That type isn't present, so it returns null which causes the exception.
