### ISSUE TITLE
MonoGameTests errors regarding 'd3dcompiler_47.dll'

### ISSUE THREAD

**Issue by uzyfeo** [mono/MonoGame#4131]
I tried to compile MonoGame myself. Everything worked out smoothly, but when I tried to test my build with MonoGameTests, there jumped few errors, all regarding loading 'd3dcompiler_47.dll' file.

I'm running Windows 7 x64 machine and tried to compile it in Visual Studio 2015 Comunnity Edition... I was following (most of the time...) guide found here https://github.com/mono/MonoGame/wiki/Tutorials:-Getting-Started-on-Windows-with-Visual-Studio
I was trying to build and run projects in solution MonoGame.Framework.Windows.sln

Any possible help? From my search so far, it seems to be somehow linked to Windows 8.1 SDK...

Example error in VertexTextureVisualTest test:
```
System.DllNotFoundException : Unable to load DLL 'd3dcompiler_47.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)

at SharpDX.D3DCompiler.D3D.D3DCompile_(Void* arg0, Void* arg1, Void* arg2, Void* arg3, Void* arg4, Void* arg5, Void* arg6, Int32 arg7, Int32 arg8, Void* arg9, Void* arg10)
at SharpDX.D3DCompiler.D3D.Compile(IntPtr srcDataRef, PointerSize srcDataSize, String sourceNameRef, ShaderMacro[] definesRef, IntPtr includeRef, String entrypointRef, String targetRef, ShaderFlags flags1, EffectFlags flags2, Blob& codeOut, Blob& errorMsgsOut)
at SharpDX.D3DCompiler.ShaderBytecode.Compile(Byte[] shaderSource, String entryPoint, String profile, ShaderFlags shaderFlags, EffectFlags effectFlags, ShaderMacro[] defines, Include include, String sourceFileName)
at TwoMGFX.EffectObject.CompileHLSL(ShaderInfo shaderInfo, String shaderFunction, String shaderProfile, String& errorsAndWarnings)
at TwoMGFX.EffectObject.CreateShader(ShaderInfo shaderInfo, String shaderFunction, String shaderProfile, Boolean isVertexShader, String& errorsAndWarnings)
at TwoMGFX.EffectObject.CompileEffect(ShaderInfo shaderInfo, String& errorsAndWarnings)
at Microsoft.Xna.Framework.Content.Pipeline.Processors.EffectProcessor.Process(EffectContent input, ContentProcessorContext context)
at MonoGame.Tests.ContentPipeline.AssetTestUtility.CompileEffect(GraphicsDevice graphicsDevice, String[] pathParts)
at MonoGame.Tests.Visual.GraphicsDeviceTest.<VertexTextureVisualTest>b__9_0(Object sender, FrameInfoEventArgs e)
at MonoGame.Tests.TestGameBase.SafeRaise(EventHandler`1 handler)
at MonoGame.Tests.Visual.VisualTestGame.Draw(GameTime gameTime)
at Microsoft.Xna.Framework.Game.DoDraw(GameTime gameTime)
at Microsoft.Xna.Framework.Game.Tick()
at MonoGame.Framework.WinFormsGameWindow.RunLoop()
at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
at MonoGame.Tests.Visual.VisualTestFixtureBase.RunMultiFrameTest(Int32 captureCount, Int32 captureStride, Single similarity, Boolean writeDiffs)
at MonoGame.Tests.Visual.GraphicsDeviceTest.VertexTextureVisualTest()
```

**Comment by tomspilman** [comment]
Try installing the latest DirectX Runtime...

http://www.microsoft.com/en-us/download/details.aspx?id=35

... that should install the d3dcompiler DLL.

**Comment by uzyfeo** [comment]
Didn't help, even after restarting my machine, still same errors :(

**Comment by trufun202** [comment]
@uzyfeo have you had any luck on this?  I'm getting the exact same error on my Windows 7 64-bit machine.

**Comment by uzyfeo** [comment]
Unfortunately no and it seems like nobody knows where's the problem...

Is it anyhow relevant anyway? I don't know severity of these errors (like if my build will not work in some cases or so...) cause it seems functional from what I tried, just throwing errors in tests :/

**Comment by trufun202** [comment]
I'm porting my game from XNA to MonoGame and I have a HLSL pixel shader that I'm trying to get in mgfx format.  The 2MGFX tool is throwing the "Unable to load DLL 'd3dcompiler_47.dll'" error.  :(

**Comment by uzyfeo** [comment]
Well I just started working so I didn't really get to part with shaders and effects :/

But this is DirectX releated, not MonoGame I think, so maybe we should ask over at SharpDX... Hmm...

**Comment by mrhelmut** [comment]
It typically is a DirectX installation issue. If the web installer above linked didn't helped, try to force install the latest DirectX runtime through [this installer instead](http://www.microsoft.com/en-us/download/details.aspx?id=8109).

**Comment by trufun202** [comment]
Thank you for your help.  I used the installer that you sent, and I'm now getting a different error:
"Unable to load DLL 'libmojoshader_64.dll': The specified module could not be found."
This happens both in the Pipeline app and when running 2mgfx.exe from the command line, using /Profile:OpenGL.
I have verified that the libmojoshader_64.dll exists in the 2mgfx.exe folder.
Here is my fx file:
sampler2D input : register(s0);
bool UseDefaultPalette = true;
float4 FromColor1 : register(C0);float4 FromColor2 : register(C1);float4 FromColor3 : register(C2);float4 FromColor4 : register(C3);float4 ToColor1 : register(C4);float4 ToColor2 : register(C5);float4 ToColor3 : register(C6);float4 ToColor4 : register(C7);
float4 CurrentColor1;float4 CurrentColor2;float4 CurrentColor3;float4 CurrentColor4;
float4 main(float2 uv : TEXCOORD) : COLOR {     float4 Color;     Color= tex2D(input , uv.xy); 
	if (!UseDefaultPalette)	{		if (Color.r == FromColor1.r && Color.g == FromColor1.g && Color.b == FromColor1.b)			return ToColor1;		else if (Color.r == FromColor2.r && Color.g == FromColor2.g && Color.b == FromColor2.b)			return ToColor2;		else if (Color.r == FromColor3.r && Color.g == FromColor3.g && Color.b == FromColor3.b)			return ToColor3;		else if (Color.r == FromColor4.r && Color.g == FromColor4.g && Color.b == FromColor4.b)			return ToColor4;	}
    return Color;}
technique Technique1{    pass Pass1    {        PixelShader = compile ps_2_0 main();    }}
Thanks again!-Chris B.
Date: Mon, 21 Sep 2015 04:55:03 -0700

**Comment by tomspilman** [comment]
> "Unable to load DLL 'libmojoshader_64.dll': The specified module could not be found."

So one of two issues here:

 Your machine is 32bit which means it can't properly run the 64bit MonoGame tools.  You can either fix your machine, try to hack 32bit support back into the MonoGame tools, or use an older version of MonoGame.  You can see our reasoning for this and some workarounds here:

  https://github.com/mono/MonoGame/issues/3365#issuecomment-69005713

The other issue is that you may have an old broken version of 'libmojoshader_64.dll'.  Replace yours with this one:

  https://github.com/MonoGame/MonoGame.Dependencies/raw/master/MojoShader/Windows/libmojoshader_64.dll

**Comment by tomspilman** [comment]
FYI.  We just made a change to the 2MGFX and MGCB tools to give a more clear error message if it detects it is running in 32bit.  See #4478.  This should make issues like this easier to diagnose.
