### ISSUE TITLE
Windows DirectX: Occasionally crashes when entering fullscreen mode

### ISSUE THREAD

**Issue by MichaelDePiazzi** [mono/MonoGame#4148]
A few of my testers keep reporting the following crash when launching my game:
```
Type: SharpDX.SharpDXException
Message: HRESULT: [0x887A0022], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_NOT_CURRENTLY_AVAILABLE/NotCurrentlyAvailable], Message: A resource is not available at the time of the call, but may become available later.

Source: SharpDX
Stack Trace:
   at SharpDX.Result.CheckError()
   at SharpDX.DXGI.SwapChain.SetFullscreenState(Bool fullscreen, Output targetRef)
   at Microsoft.Xna.Framework.Graphics.GraphicsDevice.CreateSizeDependentResources(Boolean useFullscreenParameter)
   at MonoGame.Framework.WinFormsGamePlatform.EnterFullScreen()
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at FinalDays.Client.Program.Main(String[] args)
```
The crash is intermittent, and usually it works fine if they try and launch the game a second time.

Looking at the exception details, it seems to be related to entering fullscreen mode when the game is starting up.

I've personally only experienced this crash once when using fullscreen mode before. But typically I am always running in windowed mode while testing, so that's probably why I've only seen it once.

I'm planning to take a closer look into this myself sometime soon hopefully, but I was hoping that maybe someone else might have seen this before and know what the cause is.

**Comment by Shqrdx** [comment]
Try use "graphics.HardwareModeSwitch = false" in constructor. It also significally faster than standart fullscreen switching.

**Comment by MichaelDePiazzi** [comment]
@Shqrdx Thanks for the suggestion, I'll give it a try! This crash I'm seeing will still be there in MonoGame obviously, but if this option works just the same and is faster as well then I'll use this as the solution for my game at least :)

**Comment by MichaelDePiazzi** [comment]
Just a quick update on this - I've had no further reports of this crash occurring in my game since enabling borderless fullscreen windowed mode (i.e. `GraphicsDeviceManager.HardwareModeSwitch = false`).

So for me, I consider the issue resolved (in my game). But while this is an acceptable workaround for my game, I guess the underlying issue with hardware fullscreen mode occasionally crashing is still present in MonoGame.

But since no one else has reported experiencing this problem, I'm more than happy to close this issue if you guys want. If someone else does experience it, we can always re-open this / raise a new issue.

@KonajuGames @tomspilman Thoughts?

**Comment by mrhelmut** [comment]
We get many crash reports for this error, it's the most referenced one in our crash reporter ("most", but still occasional, 9 crashes out of thousands sessions). I've never really cared about it because I was assuming it to be related to users launching the game rapidly after another DX app and made the device not yet ready.

We use ```GraphicsDeviceManager.HardwareModeSwitch = false``` by default, but we allow users to change that in the game options (because some users wanted to use the streaming feature of their Geforce, which only works with the hardware switch on). This is most probably why it is not occurring more often.

I've never experienced it while debugging. I have no clue on this one.

**Comment by mrhelmut** [comment]
I'm not into DXGI, but based on [the documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/bb174579(v=vs.85).aspx) "when this error is returned, an application can continue to run in windowed mode and try to switch to full-screen mode later".
[This documentation](https://msdn.microsoft.com/en-us/library/windows/desktop/ee417025(v=vs.85).aspx) may also provide answers to this problem.

Anyone confident enough with DXGI to tackle this?

**Comment by MichaelDePiazzi** [comment]
Ahhh... that makes some sense. I have basically zero experience with DXGI, but I'd be willing to take a look into it. Only problem is that I'm going to be too busy to look at it for at least another month...

**Comment by mrhelmut** [comment]
I've tentatively submitted a PR (#4337). Since I'm not very confident in using DXGI, this PR is mainly there to open the discussion regarding how this should be fixed.

**Comment by spunky44** [comment]
This was reported by a Steam user today, also intermittently.
I think Steam is interfering or stealing focus.

The `GraphicsDeviceManager.HardwareModeSwitch = false` workaround is not good enough for us. We want to keep the option of changing modes in fullscreen.

**Comment by spunky44** [comment]
The docs say:

DXGI_ERROR_NOT_CURRENTLY_AVAILABLE if the action failed. There are many reasons why a windowed-mode swap chain cannot switch to full-screen mode. For instance:

1. The application is running over Terminal Server.
2. - The output window is occluded.
3. - The output window does not have keyboard focus.
4. - Another application is already in full-screen mode.

Perhaps 3. is the cause. I don't know, since I cannot repro the error.
I tried mrhelmut's fix, but in my case it caused a crash.

Now I would like to try to solve it by bringing the game window to front and then calling ApplyChanges again from my game code.
This guy does something similar:
http://www.sivachandran.in/2014/06/enabling-direct3d-fullscreen-mode-from.html

**Comment by spunky44** [comment]
I made a simple fix that retries ApplyChanges a few times. It doesn't seem to have worked though, the user is still reporting the error.

**Comment by gap9269** [comment]
I can reproduce this error pretty consistently with my set-up. I have the game launching into full screen when I run it. I have 2 monitors and the game is launching onto the primary display {Window.Position = (0,0) }. 

To reproduce the error I run the game, close it, then immediately run it again and switch my mouse/keyboard focus to the OTHER display. It triggers every time I've tried this. I'm running it in debug mode in VS2013.

**Comment by Jjagg** [comment]
@gap9269 Can you try latest develop? I changed/fixed a bunch of stuff related to GraphicsDevice and Window for DX in #5139. I tried launching with focus on another monitor, but not explicitly like you mention here. If it's not fixed I'll dig into it when I have the time.

**Comment by gap9269** [comment]
When I get a few hours free I can try that, yeah. I'm running 3.4 still because of #5341. Upgrading Monogame causes my game to rebuild, which takes a very long time. I should be able to find the time over the next few days, though.

**Comment by Jjagg** [comment]
@gap9269 I can't seem to reproduce this, even with your tips above. Thanks for giving this another go!

**Comment by gap9269** [comment]
Okay, so I installed the latest develop and ran into a lot of issues using full screen with 2 monitors:

When I apply fullscreen, my cursor bugs out and gets locked to the other monitor. It's strange. The cursor seems bound by the resolution of my other monitor, which is smaller than my main one that I'm running full screen on.

Setting the resolution of the game to be "full screen" and using borderless mode works fine with the cursor, however.

At one point I did end up getting the full screen to work correctly with the cursor, not sure what combination of things I did, to be honest. I was just changing resolutions a bunch and trying full screen on and off until it finally worked. When I alt+tab though, it knocks me out of full screen and doesn't go back to full screen when I reopen the window. It's just at the same resolution in windowed mode.

It also does strange things with my other programs that I have running. Slack, for instance, kept getting its window shrunk down to a small size. 

I also noticed that my list of supported resolutions is in a jumbled order now. I'm reading them  I'm not sure if that's a 3.5 or 3.6 thing, but it's new. I'm using "GraphicsAdapter.DefaultAdapter.SupportedDisplayModes" for those.

This makes it tough to test the game crashing on start-up with the other monitor focused, of course.

**Comment by Jjagg** [comment]
> When I apply fullscreen, my cursor bugs out and gets locked to the other monitor. It's strange. The cursor seems bound by the resolution of my other monitor, which is smaller than my main one that I'm running full screen on.

Not sure what is happening here and I can't reproduce this :/ 

> When I alt+tab though, it knocks me out of full screen and doesn't go back to full screen when I reopen the window.

MonoGame does not yet handle lost device events properly. Seems like we should catch alt+tab somehow and save the fullscreen state for restoring when focus is back.

> It also does strange things with my other programs that I have running. Slack, for instance, kept getting its window shrunk down to a small size.

When doing a hardware fullscreen switch you're changing the display mode, so that's always gonna mess some stuff up. XNA seems to correctly restore the positions and sizes of other windows after exiting fullscreen though. Not sure what we can do to handle this better.

> Also the game throws an exception sometimes when I close it now. Only seems to happen after I mess with full screen.

Can you provide some details on this? 

I'd recommend just using a borderless maximized window for fullscreen rather than actually changing the display resolution. I.e. set `graphics.HardwareModeSwitch = false`. And handle scaling your game yourself. That should solve all the issues you mention and is also way more reliable than doing a hardware modeswitch. We should really get this all worked out though :(

**Comment by gap9269** [comment]
> Also the game throws an exception sometimes when I close it now. Only seems to happen after I mess with full screen.

> Can you provide some details on this?

I'm not sure what the exception is because it's thrown in Program.cs at game.Run() and closes itself immediately once the program quits a fraction of a second later. I should have tried catching it, but it wasn't consistent and wasn't all that troublesome anyway.

I prefer true full screen mode in games (and know others who feel the same way) as opposed to borderless windowed mode, but I'd settle for not changing the display mode if this were the only problem I'd found with v3.6. As for this ticket though, it seems the best solution really is to just set `graphics.HardwareModeSwitch = false`

**Comment by Jjagg** [comment]
FYI @gap9269 I made some fixes/improvements to full screen and other windowing stuff for DX in #5585.

**Comment by gap9269** [comment]
I noticed some changes when I updated to the development branch last week. I ended up doing a soft fullscreen by just setting the game and backbuffer to the computer's current resolution, then changing the window to be borderless. 

`graphics.HardwareModeSwitch = false` was doing some nasty things to my game, mostly when the game would launch with the saved settings. I don't know, it might have been a mixture of things I was doing with resolution settings. I was also noticing that with hardware fullscreen there would be a border, but switching to borderless would cause a massive framerate drop. It was very strange. I've been having issues with my displayport cable recently, so that could have been a culprit, too. Who knows. 

All in all I solved it with the soft fullscreen / borderless method. It's faster, easier, and I suppose I don't see any real drawbacks as of yet.

**Comment by Jjagg** [comment]
@MichaelDePiazzi Do these errors still occur? Do you still run your game in (or support) hardware fullscreen?

**Comment by MichaelDePiazzi** [comment]
@Jjagg I couldn't tell you. I haven't used hardware fullscreen since this. And luckily no one's asked me for it either, so I've been able to avoid it.

I have a feeling though that the issue still exists. I know @mrhelmut took a good crack at fixing this in PR #4337 before he switched to using OpenGL instead. The results of his testing seemed very positive though. The issue seemed to be caused by the graphics device not being ready for the fullscreen switch, and seemed to be resolved by retrying again a little later.

**Comment by Jjagg** [comment]
Okay, thanks :) I'll leave this open for now.
