### ISSUE TITLE
AudioEngine: FileNotFoundException HResult -2147024894 Universal Windows App

### ISSUE THREAD

**Issue by GrafSeismo** [mono/MonoGame#4416]
I try to load an xgs XAudio2 engine file with following code but fail without any idea why i do get the error message FileNotFound. The file exists at specified path. I use the current developer build 3.5.0.1148 of Monogame in a Universal Windows project. My VS 2015 Community Edition is up to date with Update1 installed.

```csharp
const string delimiter = @"\";
const string contentFolder = @"Content"; // This is normaly taken from general content path var
const string audioFolder = @"Audio" + delimiter + @"XACT" + delimiter;

// E:\Documents\Visual Studio 2015\Projects\MyProject\MyProject\bin\WindowsUAP\x86\Debug\
var root = Package.Current.InstalledLocation.Path.Replace(@"AppX", "");
// E:\Documents\Visual Studio 2015\Projects\MyProject\MyProject\bin\WindowsUAP\x86\Debug\Content\Audio\XACT\
var path = root + contentFolder + delimiter + audioFolder;
// E:\Documents\Visual Studio 2015\Projects\MyProject\MyProject\bin\WindowsUAP\x86\Debug\Content\Audio\XACT\Audiomaster.xgs
var file = path + @"Audiomaster.xgs";
// Following line crash with error see below
engine = new AudioEngine(file);
```

System.IO.FileNotFoundException was unhandled by user code
  HResult=-2147024894
  Message=E:\Documents\Visual Studio 2015\Projects\MyProject\MyProject\bin\WindowsUAP\x86\Debug\Content\Audio\XACT\Audiomaster.xgs
  Source=MonoGame.Framework
  StackTrace:
       at Microsoft.Xna.Framework.TitleContainer.OpenStream(String name)
       at Microsoft.Xna.Framework.Audio.AudioEngine..ctor(String settingsFile, TimeSpan lookAheadTime, String rendererId)
       at Microsoft.Xna.Framework.Audio.AudioEngine..ctor(String settingsFile)
       at MyProject.Engine.Manager.AudioManager..ctor(IOptionsManager optionsManager, String contentFolder)
       at MyProject.Engine.Engine.Initialize()
       at Microsoft.Xna.Framework.Game.DoInitialize()
       at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
       at MonoGame.Framework.XamlGame`1.Create(String launchParameters, CoreWindow window, SwapChainPanel swapChainPanel)
       at MyProject.GamePage..ctor()
       at MyProject.MyProject_XamlTypeInfo.XamlTypeInfoProvider.Activate_0_GamePage()
       at MyProject.MyProject_XamlTypeInfo.XamlUserType.ActivateInstance()
  InnerException:

**Comment by KonajuGames** [comment]
It looks like you are trying to generate an absolute path to load a file from the Content folder.  It doesn't work that way.  The AudioEngine is using TitleContainer.OpenStream() internally, which needs a relative path.  In this case, the content folder and the path inside the content folder.  Windows apps are packaged into an appx package that does not use absolute paths.

**Comment by GrafSeismo** [comment]
How do i handle subfolders than?

**Comment by KonajuGames** [comment]
The same as you were doing.  Just leave out `root`.  And .NET has `Path.Combine(path1,path2,...)` designed to build paths from separate components.

**Comment by GrafSeismo** [comment]
Ok, that did it, thank you very much!
