### ISSUE TITLE
Stencil buffer doesn't work on Mac

### ISSUE THREAD

**Issue by prime31** [mono/MonoGame#4434]
The most stripped down repro I can come up with is below. This example sets up a DepthStencilState that should only write when the stencil buffer has a 1 in it. So, since nothing at all is ever written to the stencil buffer nothing should ever be end up in the framebuffer. The actual output is that the texture is written to the framebuffer when it should not ever pass the stencil test.

```csharp
	public class Game1 : Game
	{
		GraphicsDeviceManager graphics;
		SpriteBatch _spriteBatch;
		Texture2D _maskTex;

		// only write when the stencil buffer has 1
		public static DepthStencilState EqualStencilState = new DepthStencilState() {
			StencilEnable = true,
			StencilFunction = CompareFunction.Equal,
			StencilPass = StencilOperation.Keep,
			ReferenceStencil = 1,
			DepthBufferEnable = false,
		};


		public Game1()
		{
			graphics = new GraphicsDeviceManager( this );
			graphics.PreferredDepthStencilFormat = DepthFormat.Depth24Stencil8;
			Content.RootDirectory = "Content";	            
		}


		protected override void LoadContent()
		{
			// Create a new SpriteBatch, which can be used to draw textures.
			_spriteBatch = new SpriteBatch( GraphicsDevice );
			_maskTex = Content.Load<Texture2D>( "mask" );
		}


		protected override void Draw( GameTime gameTime )
		{
			GraphicsDevice.Clear( Color.Transparent );

			_spriteBatch.Begin( SpriteSortMode.Immediate, null, SamplerState.PointClamp, EqualStencilState, null, null );
			_spriteBatch.Draw( _maskTex, new Vector2( 200, 200 ), Color.White );
			_spriteBatch.End();

			base.Draw( gameTime );
		}
	}
```

**Comment by tgjones** [comment]
I've used this code to create a test case, but I can't run this (or any other) visual test on OpenGL. I get a stack trace like this:

```
System.ArgumentNullException : Value cannot be null.
Parameter name: source

   at System.Linq.Enumerable.OfType[TResult](IEnumerable source)
   at MonoGame.Tests.Visual.VisualTestFixtureBase.WriteFrameDiffs() in C:\Users\Tim Jones\Documents\GitHub\MonoGame\Test\Framework\Visual\VisualTestFixtureBase.cs:line 227
   at MonoGame.Tests.Visual.VisualTestFixtureBase.RunMultiFrameTest(Int32 captureCount, Int32 captureStride, Single similarity, Boolean writeDiffs) in C:\Users\Tim Jones\Documents\GitHub\MonoGame\Test\Framework\Visual\VisualTestFixtureBase.cs:line 169
   at MonoGame.Tests.Visual.VisualTestFixtureBase.RunSingleFrameTest(Single similarity, Boolean writeDiffs) in C:\Users\Tim Jones\Documents\GitHub\MonoGame\Test\Framework\Visual\VisualTestFixtureBase.cs:line 123
   at MonoGame.Tests.Visual.DepthStencilStateTest.VisualTestStencilBuffer() in C:\Users\Tim Jones\Documents\GitHub\MonoGame\Test\Framework\Visual\DepthStencilStateTest.cs:line 153
```

@tomspilman, is this a known issue? I debugged it, but it's confusing - the root cause seems to a "thread was being aborted" exception.

**Comment by tomspilman** [comment]
> is this a known issue? 

Well we know the OpenGL path has issues when running under the unit test runner.  I think we need to start there, fix those problems, then circle back to this specific one.

**Comment by prime31** [comment]
Sigh. I tracked this one down and its not an issue with MonoGame. It turns out the PCL DLL defines DepthFormat like this:

![](https://files.gitter.im/prime31/cNxM/bad.png)

MonoGame source defines it like this:

![](https://files.gitter.im/prime31/zeO7/good.png)

**Comment by tgjones** [comment]
@prime31 That enum value change was made here: 89b774c9a98ac28a7b74ac100222545b9d6a4e8c. So I guess the PCL DLLs you're using haven't been updated for a while.

**Comment by prime31** [comment]
The PCL hasnt been updated in ages. I might check the CocosSharp source and see if their PCL is up to date.

**Comment by Rennan24** [comment]
Did anyone ever figure this issue out? It was marked as closed but it's still draws the texture even though the stencil buffer is clear. I Know it says that his PCL wasn't updated but I'm not using a PCL and this is still happening. Also note I'm fairly new to this so forgive me if I don't quite understand, since the way I'm doing it now is just creating a RenderTarget2D and doing the stencil test on that, but I don't get why I need the RenderTarget2D and why it just doesn't work on the frame buffer.

**Comment by prime31** [comment]
Stencil buffer definitely works like a champ when you use the correct enum values. Your issue is probably that you arent setting the correct DepthFormat on your RenderTargets.

**Comment by Rennan24** [comment]
The thing is I have it working with RenderTargets, but is there no way to have it work without creating RenderTargets?

**Comment by Rennan24** [comment]
My Code that works when render targets are involved, but not when they aren't and I'm not sure if that is supposed to be how it works or not, so I just wanted some clarification.

```CSharp
public class GameStart : Game
{
	GraphicsDeviceManager graphics;
	SpriteBatch spriteBatch;
	Texture2D cat, pixel;
	RenderTarget2D canvas;
	// only write when the stencil buffer has 1
	DepthStencilState EqualStencilState = new DepthStencilState {
		StencilEnable = true,
		StencilFunction = CompareFunction.Equal,
		StencilPass = StencilOperation.Keep,
		ReferenceStencil = 1,
		DepthBufferEnable = false,
	};

	//Always Increment the stencil buffer by 1
	DepthStencilState IncrementStencilState = new DepthStencilState {
		StencilEnable = true,
		StencilFunction = CompareFunction.Always,
		StencilPass = StencilOperation.Increment,
		ReferenceStencil = 1,
		DepthBufferEnable = false,
	};

	public GameStart ( )
	{
		//It's initialized with the correct depth format
		graphics = new GraphicsDeviceManager ( this ) {
			PreferredDepthStencilFormat = DepthFormat.Depth24Stencil8,
		};

		IsMouseVisible = true;
		Content.RootDirectory = "Content";
	}

	protected override void Initialize ( )
	{
		spriteBatch = new SpriteBatch ( GraphicsDevice );
		canvas = new RenderTarget2D ( GraphicsDevice, 800, 600, false, SurfaceFormat.Color, DepthFormat.Depth24Stencil8 );
		pixel = new Texture2D ( GraphicsDevice, 1, 1 ); //Creates a pixel for the Stencil Rect
		pixel.SetData ( new Color[ ] { Color.White } ); //Fills the pixel with 1 White pixel
		Components.Add ( new InputManager ( this ) );
		base.Initialize ( );
	}

	protected override void LoadContent ( )
	{
		cat = Content.Load<Texture2D> ( "Believe Cat" );
		base.LoadContent ( );
	}

	protected override void Draw ( GameTime gameTime )
	{
		//When the RenderTargets are used it works, but not when they aren't :(
		//GraphicsDevice.SetRenderTarget ( canvas );
		GraphicsDevice.Clear ( ClearOptions.Target | ClearOptions.Stencil, Color.Transparent, 1f, 0 );

		//Draws a filled rectangle with a stretched white pixel, meant to be a stencil
		spriteBatch.Begin ( depthStencilState: IncrementStencilState );
		spriteBatch.Draw ( pixel, new Rectangle ( 0, 0, 400, 400 ), Color.White );
		spriteBatch.End ( );

		//Draws the cat that should be cut with the stencil
		spriteBatch.Begin ( depthStencilState: EqualStencilState );
		spriteBatch.Draw ( cat, Vector2.Zero, Color.White );
		spriteBatch.End ( );

		//GraphicsDevice.SetRenderTarget ( null );

		//spriteBatch.Begin ( );
		//spriteBatch.Draw ( canvas, Vector2.Zero, Color.White );
		//spriteBatch.End ( );

		base.Draw ( gameTime );
	}
}
```
