### ISSUE TITLE
Pipeline tool can't find Freetype6.dll

### ISSUE THREAD

**Issue by Ellesent** [mono/MonoGame#4504]
When trying to build a spritefont in the content pipeline, it fails because it can't find the freetype6.dll, despite this .dll being in the monogame tools folder. I have tried multiple versions, and all of them have this issue.

This is the message when building the font:

Building Font C:\WINDOWS\Fonts\arial.ttf
System.DllNotFoundException: Unable to load DLL 'freetype6.dll': The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at SharpFont.FT.FT_Init_FreeType(IntPtr& alibrary)
   at SharpFont.Library..ctor()
   at Microsoft.Xna.Framework.Content.Pipeline.Graphics.SharpFontImporter.Import(FontDescription options, String fontName)
   at Microsoft.Xna.Framework.Content.Pipeline.Processors.FontDescriptionProcessor.ImportFont(FontDescription options, Single& lineSpacing, Int32& yOffsetMin, ContentProcessorContext context, String fontName)
   at Microsoft.Xna.Framework.Content.Pipeline.Processors.FontDescriptionProcessor.Process(FontDescription input, ContentProcessorContext context)

**Comment by KonajuGames** [comment]
Try the solution here.
http://community.monogame.net/t/monogame-noob-unable-to-load-freeimage/6255
Let us know if this works for you.

**Comment by Ellesent** [comment]
Hello thank you for getting back to me! It worked like a charm thanks for the help and sorry for not finding this solution beforehand. Thanks again!

**Comment by mdrejhon** [comment]
Solution doesn't work anymore!  
I am using Visual Studio Community 2017.

Microsoft has removed VC++ 2012 Redistributable.

![image](https://cloud.githubusercontent.com/assets/1774867/26470040/373f3268-416a-11e7-933e-62bdb0135a04.png)

**Comment by diolive** [comment]
Installed from https://www.microsoft.com/en-us/download/details.aspx?id=30679, font building now is working.

**Comment by Hammerstad** [comment]
Faced this issue using the dev / 3.8 branch. Turned out I had to install VC++ redist 2010 x64 
https://www.microsoft.com/en-us/download/details.aspx?id=14632
