### ISSUE TITLE
OculusRift via OculusWrap Support

### ISSUE THREAD

**Issue by MrBenjammin** [mono/MonoGame#4640]
Hey, I've been working on some basic Oculus Rift support in a hobby project and Tom Spillman asked me post about what was missing in MonoGame for Oculus SDK. I've mostly got VR going with a Oculus SDK wrapper called OculusWrap:
https://oculuswrap.codeplex.com/
It uses DirectX11 through SharpDX so it wasn't too bad to port over the demo and I have a working project in MonoGame. However there's one main thing missing that I've encountered so far to get it properly integrated into MonoGame using mainly MonoGame API(rather than messily bypassing it with SharpDX).

The render targets are required in their SharpDX form, which means they are very awkward and live outside of MonoGame currently in my code. Being created in SharpDX.  Since I have to have them in this form pass to the SDK. It would be useful to have a ".Handle" perhaps similar to GraphicsDevice.Handle on DirectX11 platforms that returns an object we can cast to their SharpDX internal representations for Texture/Texture2D/RenderTarget2D.

This would allow for the creation of the targets required by the Oculus SDK with just new RenderTarget2Ds inside MonoGame and also for them to be handled normally in all other parts of MonoGame such as altering/drawing these targets. An example of what currently doesn't work without interrupting MonoGames drawing is the Mirrored screen mode. The Oculus SDK populates a target with what the user sees to draw on the monitor screen. Without interfering with MonoGames internal drawing with SharpDX(which seems to break rendering down the line) I can't draw this target to screen, since it isn't a MonoGame RenderTarget2D. Where as if I could setup all the textures within MonoGame I can simply draw this on a Quad to screen or via SpriteBatch.

**Comment by tomspilman** [comment]
This issue should include getting a template put together.  https://github.com/mono/MonoGame/issues/4409

**Comment by Danthekilla** [comment]
Was any progress made on this so far this year? 

Even if it is only partly working I would be happy to finish it myself and make a pull request for it.

Just wondering so I don't unnecessarily start from scratch.

**Comment by KonajuGames** [comment]
I haven't seen any progress on it.  Very few MonoGame developers with an Oculus I think.

**Comment by steemwheedle** [comment]
I managed to get the OculusRift working with MonoGame. I made a small C++ dll based on the Oculus SDK to PInvoke into. 
If you're interested, I don't mind sharing the code. I don't have a proper MonoGame sample ready though, as I integrated it into my game engine. 
I had to make a few small changes to MonoGame. I posted about it in this thread: 

http://community.monogame.net/t/so-vr-ar/6839/6

**Comment by Danthekilla** [comment]
I would be very interested in the code, thanks very much.

Have you had many issues with working with Monogame and oculus.

I will have a read of that thread.

Let me know when you can post the code somewhere, or if you can send me a link etc...

**Comment by steemwheedle** [comment]
I uploaded the code to https://github.com/steemwheedle/OculusRift4MonoGame.git
It contains the source code for the C++ dll and a Monogame sample project. The sample project is also available as a precompiled exe. Instructions on how to build are in the readme.

I haven't done a whole lot yet with the Oculus Rift in MonoGame, but so far it went pretty smoothly. No serious problems yet that I could blame MonoGame for.

**Comment by nkast** [comment]
@steemwheedle,  I tried to run the prebuild OculusRiftSample.exe and am getting the following error:

`Unhandled Exception: SharpDX.SharpDXException: HRESULT: [0x80070057], Module: [General], ApiCode: [E_INVALIDARG/Invalid Arguments], Message: The parameter is incorrect.

   at SharpDX.Result.CheckError()
   at SharpDX.Direct3D11.Device.CreateTexture2D(Texture2DDescription& descRef, DataBox[] initialDataRef, Texture2D texture2DOut)
   at Microsoft.Xna.Framework.Graphics.Texture2D.CreateTexture()
   at Microsoft.Xna.Framework.Graphics.Texture2D..ctor(GraphicsDevice graphicsDevice, Int32 width, Int32 height, Boolean mipmap, SurfaceFormat format, SurfaceType type, Boolean shared, Int32 arraySize)
   at OculusRiftSample.TheGame.LoadContent()
   at Microsoft.Xna.Framework.Game.Initialize()
   at OculusRiftSample.TheGame.Initialize()
   at Microsoft.Xna.Framework.Game.DoInitialize()
   at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
   at OculusRiftSample.Program.Main(String[] args)`

do you have any idea?

**Comment by nkast** [comment]
@MrBenjammin Will you migrate your project to github?

**Comment by nkast** [comment]
OK, I managed to rebuild it. At some point it failed, probably because i don't have an Oculus device to test it with.  but seems ok.

**Comment by nkast** [comment]
@steemwheedle, 

OK, I managed to rebuild it. At some point it failed, probably because i don't have an Oculus device to test it with. but seems ok.

**Comment by steemwheedle** [comment]
@nkast I never tried without the Oculus Rift connected. It does make sense though that the texture would be 0x0 in that case, because it tries to get the recommended texture size from the Rift. Error checking and reporting is definitely not that great atm. Ideally it would still launch without a Rift and display stuff on the monitor only. 

Ok, I will add an MIT license file.

**Comment by nkast** [comment]
Thanks!
