### ISSUE TITLE
Issues with FBX

### ISSUE THREAD

**Issue by emersont1** [mono/MonoGame#4691]
#Model Issues with FBX

``` csharp
    public class Game1 : Game
    {
        Model myModel;
        GraphicsDeviceManager graphics;
        SpriteBatch spriteBatch;
        Vector3 modelPosition = Vector3.Zero;
        float modelRotation = 0.0f;

        // Set the position of the camera in world space, for our view matrix.
        Vector3 cameraPosition = new Vector3(0.0f, 50.0f, 5000.0f);

        public Game1()
        {
            graphics = new GraphicsDeviceManager(this);
            Content.RootDirectory = "Content";
        }

        /// <summary>
        /// LoadContent will be called once per game and is the place to load
        /// all of your content.
        /// </summary>
        protected override void LoadContent()
        {
            // Create a new SpriteBatch, which can be used to draw textures.
            spriteBatch = new SpriteBatch(GraphicsDevice);
            myModel = Content.Load<Model>("Quattro");
            // TODO: use this.Content to load your game content here
        }

    }
}


```

Exception Details

```
Microsoft.Xna.Framework.Content.ContentLoadException was unhandled
  HResult=-2146233088
  Message=Could not load Quattro asset as a non-content file!
  Source=MonoGame.Framework
  StackTrace:
       at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject)
       at Microsoft.Xna.Framework.Content.ContentManager.Load[T](String assetName)
       at _3D_Game1.Game1.LoadContent() in K:\Documents\Visual Studio 2015\Projects\3D Game1\3D Game1\Game1.cs:line 52
       at Microsoft.Xna.Framework.Game.Initialize()
       at _3D_Game1.Game1.Initialize() in K:\Documents\Visual Studio 2015\Projects\3D Game1\3D Game1\Game1.cs:line 41
       at Microsoft.Xna.Framework.Game.DoInitialize()
       at Microsoft.Xna.Framework.Game.Run(GameRunBehavior runBehavior)
       at Microsoft.Xna.Framework.Game.Run()
       at _3D_Game1.Program.Main() in K:\Documents\Visual Studio 2015\Projects\3D Game1\3D Game1\Program.cs:line 17
       at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       at System.Threading.ThreadHelper.ThreadStart()
  InnerException: 
       HResult=-2146233088
       Message=Incorrect type reader index found!
       Source=MonoGame.Framework
       StackTrace:
            at Microsoft.Xna.Framework.Content.ContentReader.InnerReadObject[T](T existingInstance)
            at Microsoft.Xna.Framework.Content.ContentReader.ReadSharedResources()
            at Microsoft.Xna.Framework.Content.ContentReader.ReadAsset[T]()
            at Microsoft.Xna.Framework.Content.ContentManager.ReadAsset[T](String assetName, Action`1 recordDisposableObject)
       InnerException: 

```
+ Version: MonoGame 3.5 for VisualStudio
+ Previous Versions: None
+ VisualStudio 2015 Community, Windows 10 Home x64
+ Cross platform GL project type
+ [FBX](http://puu.sh/o0unl/c28cdabf64.FBX)
+ [XNB](http://puu.sh/o0uoB/526fd23767.xnb)
+ [MGCB](http://puu.sh/o0up2/25e6dd812e.mgcb)
+ Works with this [OBJ](http://puu.sh/o0uHV/75530c5018.obj)

**Comment by tomspilman** [comment]
This is great... thanks @emersont1 !

**Comment by InfiniteProductions** [comment]
May it help, I've tried with XNA Model viewer (from Charles B. Owen) and it works, but model have missing triangles (side wall depth, one part of the roof).

@emersont1 : it would be also helpful to know which options you've used while exporting the object I guess.

**Comment by emersont1** [comment]
i got it on a royalty free model site so i can't help with the export options

**Comment by InfiniteProductions** [comment]
You can still ask the author, or download scene if available (on turbosquid, some authors provide both object in various format like FBX, and 3DSMax full scene).

Maybe the issue comes from:
object contains 110 elements and 12 materials

Such quite huge amount of sub-meshes doesn't suit games usually, in this object even some small element on top of windows are separated meshes (I don't even think destructible models work this way).

**Comment by emersont1** [comment]
right. There are 3ds and 3ds Max files, however they did put
>Building made for **games** and animation. Easy to use and adding textures. Simple construction and detailed facade.

**Comment by mgarstenauer** [comment]
I can open the model when using my own model processor and model class. The FBX is fine, except for some triangles with wrong normals/winding order. This means that the model importer is ok.
I guess it is a bug in the MonoGame model processor/writer/reader, which appears when writing/reading shared resources.

**Comment by tomspilman** [comment]
> I guess it is a bug in the MonoGame model processor/writer/reader, which appears when writing/reading shared resources.

That sounds very possible... we need to debug that and add a unit test to avoid it in the future.
