### ISSUE TITLE
NUnit Failure

### ISSUE THREAD

**Issue by tomspilman** [mono/MonoGame#5042]
We're currently experiencing some sort of error running unit tests under TeamCity.

A build from a July 18th shows 803 tests run:

http://teamcity.monogame.net/viewLog.html?buildId=18960&buildTypeId=MonoGame_TestWindows&tab=buildResultsDiv

A build a few days later on July 22nd shows only 398 tests run:

http://teamcity.monogame.net/viewLog.html?buildId=19164&buildTypeId=MonoGame_TestWindows&tab=buildResultsDiv

Looking further the unit tests seem to be failing mid run:

```
[17:41:56]E:			 [MonoGameTests.exe] MonoGame.Tests.Framework.SpriteFontNonVisualTest.MeasureString_returns_correct_values("JingJing","%",21,45) (2s)
[17:41:57]E:				 [MonoGame.Tests.Framework.SpriteFontNonVisualTest.MeasureString_returns_correct_values("JingJing","%",21,45)] [Test Error Output]
System.NullReferenceException: Object reference not set to an instance of an object.
   at NUnit.Core.TestSuite.Run(EventListener listener, ITestFilter filter)
   at NUnit.Core.TestSuite.RunAllTests(TestResult suiteResult, EventListener listener, ITestFilter filter)
   at NUnit.Core.TestSuite.RunSuite(EventListener listener, ITestFilter filter)
   at NUnit.Core.TestSuite.RunSuiteInContext(EventListener listener, ITestFilter filter)
   at NUnit.Core.TestSuite.Run(EventListener listener, ITestFilter filter)
   at NUnit.Core.SimpleTestRunner.Run(EventListener listener, ITestFilter filter, Boolean tracing, LoggingThreshold logLevel)
   at NUnit.Core.TestRunnerThread.TestRunnerThreadProc()
[17:41:57]W:				 [MonoGame.Tests.Framework.SpriteFontNonVisualTest.MeasureString_returns_correct_values("JingJing","%",21,45)] [Test Error Output]
Unhandled exception in remote appdomain: System.ApplicationException: Exception in TestRunnerThread ---> System.NullReferenceException: Object reference not set to an instance of an object.
   at NUnit.Core.TestSuite.Run(EventListener listener, ITestFilter filter)
   at NUnit.Core.TestSuite.RunAllTests(TestResult suiteResult, EventListener listener, ITestFilter filter)
   at NUnit.Core.TestSuite.RunSuite(EventListener listener, ITestFilter filter)
   at NUnit.Core.TestSuite.RunSuiteInContext(EventListener listener, ITestFilter filter)
   at NUnit.Core.TestSuite.Run(EventListener listener, ITestFilter filter)
   at NUnit.Core.SimpleTestRunner.Run(EventListener listener, ITestFilter filter, Boolean tracing, LoggingThreshold logLevel)
   at NUnit.Core.TestRunnerThread.TestRunnerThreadProc()
   --- End of inner exception stack trace ---
   at NUnit.Core.TestRunnerThread.TestRunnerThreadProc()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

This doesn't look like any failure in the unit tests themselves...  this looks like some failure within NUnit itself.

I don't know why it suddenly started failing... there have been no changes to how unit tests are run in quite a while.

Note we're currently running on an old version of NUnit 2.6.0 which is from February 20, 2012.  Could be we should just upgrade to the latest NUnit release to solve this.

**Comment by Jjagg** [comment]
I ran into this when running the test locally so I'm digging into this. There are two tests were I had this happen, SpriteFontNonVisualTest and GameComponentTest. It seems like this has to do with disposing a Game.

**Comment by Jjagg** [comment]
@tomspilman The issue here is that DynamicSoundEffectInstances are not disposed when Game is disposed. The Audio testing forgot to dispose some SoundEffects and on the first test after that that uses a Game crashes when it's disposed and attempts to dispose the XAudio MasterVoice [here](https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Audio/SoundEffect.XAudio.cs#L353). I have no idea why the tests sometimes just worked on the build server, but luckily they consistently failed locally, which helped pinpoint the issue. I got it down to running one audio test and one test that uses a Game and noticed it didn't dispose a sound effect (https://github.com/mono/MonoGame/blob/develop/Test/Framework/Audio/DynamicSoundEffectInstanceTest.cs#L172). Disposing it fixed the issue.

I'll make sure DynamicSoundEffects are disposed in the tests. Maybe dynamic sound effects also be added to some static collection so they can always be properly disposed?

**Comment by tomspilman** [comment]
> Maybe dynamic sound effects also be added to some static collection so they can always be properly disposed?

Maybe...  we don't really do that sort of tracking with sound effects like we do with all the types derived from `GraphicsResource`.  But maybe we should to ensure proper cleanup.

@KonajuGames @dellis1972 ?

**Comment by KonajuGames** [comment]
We only track GraphicsResource objects created through the ContentManager.
Objects created manually such as `new Texture2D` or `Texture2D.FromStream`
require the dev to dispose of the objects.  DynamicSoundEffectInstance
would be similar as it is manually created and managed by the dev.

**Comment by Jjagg** [comment]
> DynamicSoundEffectInstance would be similar as it is manually created and managed by the dev.

Yeah, that makes sense.

**Comment by tomspilman** [comment]
> We only track GraphicsResource objects created through the ContentManager.

That isn't exactly true.  We do keep a list of all `GraphicsResources` in `GraphicsDevice`:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/GraphicsDevice.cs#L112

And you can see here how we force dispose them on `GraphicsDevice` shutdown:

https://github.com/mono/MonoGame/blob/develop/MonoGame.Framework/Graphics/GraphicsDevice.cs#L472

I don't see a problem with doing a similar-ish thing with sound system resources.  Especially if the alternative is having `Game` shutdown crash.

**Comment by KonajuGames** [comment]
I didn't realise we kept that list. In that case, sounds should do the same thing.
